// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eNOTICE_MSG_TYPE
    implements ProtoEnum {
  /**
   * ������Ϣ
   */
  NOTICE_MSG_TYPE_FRD(1),
  /**
   * ������Ϣ
   */
  NOTICE_MSG_TYPE_FAM(2),
  /**
   * ��������Ϣ
   */
  NOTICE_MSG_TYPE_TG(3),
  /**
   * ���Ϣ
   */
  NOTICE_MSG_TYPE_ACTIVE(4);

  private final int value;

  eNOTICE_MSG_TYPE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
