// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eNOTICE_CTRL_STYLE
    implements ProtoEnum {
  /**
   * δ֪
   */
  NOTICE_CTRL_UNKNOWN(0),
  /**
   * ���� ��������
   */
  NOTICE_CTRL_REQ_ADD(1),
  /**
   * ���� �������
   */
  NOTICE_CTRL_REQ_INVITE(2),
  /**
   * �ظ� ͬ��
   */
  NOTICE_CTRL_REP_ACCEPT(3),
  /**
   * �ظ� �ܾ�
   */
  NOTICE_CTRL_REP_DENY(4),
  /**
   * ��� �˳�
   */
  NOTICE_CTRL_RET_EXIT(5),
  /**
   * ��� �����
   */
  NOTICE_CTRL_RET_GETOUT(6),
  /**
   * ��� ����������Ա
   */
  NOTICE_CTRL_RET_ADD(7),
  /**
   * ��� ��ɢ
   */
  NOTICE_CTRL_RET_DISS(8),
  /**
   * ��ʾ֪ͨ��Ϣ
   */
  NOTICE_CTRL_DISPLAY_MSG(9);

  private final int value;

  eNOTICE_CTRL_STYLE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
