// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\commonMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum ePB_COM_USERSTATUS
    implements ProtoEnum {
  /**
   * ��ʾ��������״̬���û�
   */
  OFFLINE(0),
  /**
   * ��ʾ������Ϸ����״̬���û�
   */
  IN_GAME(1),
  /**
   * ��ʾ������������״̬���û�
   */
  IN_CHATROOM(2);

  private final int value;

  ePB_COM_USERSTATUS(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
