// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum ePB_ADDFAM_REPCMD
    implements ProtoEnum {
  /**
   * ���ܼ������
   */
  AFM_ACCEPT(0),
  /**
   * �ܾ��������
   */
  AFM_REJECT(1),
  /**
   * ���þܾ��������
   */
  AFM_DENY(2);

  private final int value;

  ePB_ADDFAM_REPCMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
