// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum ePB_MSG_STYLE
    implements ProtoEnum {
  /**
   * �ı�
   */
  CHAT_MSG_STYLE_TEXT(1),
  /**
   * ͼƬ
   */
  CHAT_MSG_STYLE_PIC(2),
  /**
   * ����
   */
  CHAT_MSG_STYLE_VOICE(4),
  /**
   * ��Ƶ
   */
  CHAT_MSG_STYLE_VEDIO(8),
  /**
   * ����
   */
  CHAT_MSG_STYLE_LINK(16);

  private final int value;

  ePB_MSG_STYLE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
