// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum ePB_CHAT_ZONE
    implements ProtoEnum {
  /**
   * ������ͨ����
   */
  CM_ZONE_FAM_NORMAL(1),
  /**
   * �������Ա����
   */
  CM_ZONE_FAM_MANAGER(2),
  /**
   * ��������
   */
  CM_ZONE_PERSONAL(3),
  /**
   * ����������
   */
  CM_ZONE_TALKGROUP(4),
  /**
   * �̼�
   */
  CM_ZONE_SELLER(5),
  /**
   * ϵͳ
   */
  CM_ZONE_SYS(6);

  private final int value;

  ePB_CHAT_ZONE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
