// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum ePB_ADDFRD_REPCMD
    implements ProtoEnum {
  /**
   * ���ܼ�Ϊ����
   */
  AFR_ACCEPT(0),
  /**
   * �ܾ���Ϊ����
   */
  AFR_REJECT(1);

  private final int value;

  ePB_ADDFRD_REPCMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
