// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum ePB_ADDFRD_REQ_RET
    implements ProtoEnum {
  /**
   * �ɹ�����
   */
  ADDFRD_REQ_SUCC(0),
  /**
   * ����ʧ��
   */
  ADDFRD_REQ_FAIL(1),
  /**
   * ���ǶԷ�����
   */
  ADDFRD_REQ_MEMBER(2),
  /**
   * ���Ǻ�����
   */
  ADDFRD_REQ_BLACK(3),
  /**
   * �ظ��ύ
   */
  ADDFRD_REQ_REPOST(4);

  private final int value;

  ePB_ADDFRD_REQ_RET(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
