// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_PUSH_MSG
    implements ProtoEnum {
  /**
   * token err
   */
  eRS_PUSH_MSG_TOKENERR(1),
  /**
   * fail
   */
  eRS_PUSH_MSG_FAIL(2),
  eRS_PUSH_MSG_SUC(3);

  private final int value;

  eRS_PUSH_MSG(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
