// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_GT_TGUSER_Ret
    implements ProtoEnum {
  /**
   * �ɹ�
   */
  eRS_GT_TGU_SUC(0),
  /**
   * δ֪����
   */
  eRS_GT_TGU_FAIL_UNKNOWN(1),
  /**
   * Ⱥ�鲻����
   */
  eRS_GT_TGU_FAIL_NOTG(2),
  /**
   * ���������鴴����
   */
  eRS_GT_TGU_FAIL_NOCREATER(3);

  private final int value;

  eRS_GT_TGUSER_Ret(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
