// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_USER_AT
    implements ProtoEnum {
  /**
   * APP����
   */
  USER_AT_APP(1),
  /**
   * ��Ϣ�б����
   */
  USER_AT_MSGLIST(2),
  /**
   * �������
   */
  USER_AT_FAMILY(3),
  /**
   * �����������
   */
  USER_AT_PERSONAL(4),
  /**
   * �������Ա����
   */
  USER_AT_MANAGER(5),
  /**
   * ���������
   */
  USER_AT_TALKGROUP(6),
  /**
   * ֪ͨ��Ϣ����
   */
  USER_AT_NOTCIEMSG(7),
  /**
   * �̼һ�б����
   */
  USER_AT_SELLER(8),
  /**
   * ϵͳ��Ϣ����
   */
  USER_AT_SYS(9);

  private final int value;

  eRS_USER_AT(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
