// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_Oprate_Relation_Ret
    implements ProtoEnum {
  eRS_OR_SUC(0),
  eRS_OR_FAIL(1),
  /**
   * ���������Ѿ��м���
   */
  eRS_OR_HAS_FAMILY(2),
  /**
   * �������޼���
   */
  eRS_OR_NO_FAMILY(3),
  /**
   * �ظ��ύ����
   */
  eRS_OR_REPOST_INVITE(4),
  /**
   * δ֪����
   */
  eRS_OR_UNKNOWN(5);

  private final int value;

  eRS_Oprate_Relation_Ret(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
