// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_Invite_Ret
    implements ProtoEnum {
  /**
   * ����
   */
  eRS_IR_ACCEPT(0),
  /**
   * �ܾ�
   */
  eRS_IR_REJECT(1),
  /**
   * ����
   */
  eRS_IR_IGNORE(2);

  private final int value;

  eRS_Invite_Ret(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
