// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_SendChat_Ret
    implements ProtoEnum {
  /**
   * �ɹ�
   */
  RS_SC_SUCC(0),
  /**
   * ����̫Ƶ���������û�ʱ��������6�룩
   */
  RS_SC_ERR_FREQUENTLY(1),
  /**
   * ��ֹ����
   */
  RS_SC_ERR_LIMIT_CHAT(2),
  /**
   * û�з���ͼƬ��Ȩ��
   */
  RS_SC_ERR_LIMIT_PICTURE(3),
  /**
   * û�з���������Ȩ��
   */
  RS_SC_ERR_LIMIT_VOICE(4),
  /**
   * û�з�����Ƶ��Ȩ��
   */
  RS_SC_ERR_LIMIT_VIDEO(5),
  /**
   * ����������Ϣʧ��
   */
  RS_SC_ERR_SAVE_FAIL(6),
  /**
   * ����Ϊ������
   */
  RS_SC_ERR_IS_BLACK(7),
  /**
   * @���ʹ�������
   */
  RS_SC_ERR_OUTBOUND_CNT(8),
  /**
   * web��֤@����ʧ��
   */
  RS_SC_ERR_WEB_VERIFY(9);

  private final int value;

  eRS_SendChat_Ret(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
