// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_GetOut_Family_Ret
    implements ProtoEnum {
  /**
   * �ɹ�
   */
  RS_GOF_SUCC(0),
  /**
   * ʧ��
   */
  RS_GOF_ERR_FAIL(1),
  /**
   * ��Ȩ��
   */
  RS_GOF_ERR_NO_ACCESS(2);

  private final int value;

  eRS_GetOut_Family_Ret(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
