// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_EXIT_TG_Ret
    implements ProtoEnum {
  /**
   * �ɹ�
   */
  eRS_EXIT_TG_SUC(0),
  /**
   * δ֪����
   */
  eRS_EXIT_TG_FAIL_UNKNOWN(1),
  /**
   * �����鲻����
   */
  eRS_EXIT_TG_FAIL_NOTG(2);

  private final int value;

  eRS_EXIT_TG_Ret(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
