// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum eRS_COMMON_ZONE
    implements ProtoEnum {
  /**
   * ��ע
   */
  eRS_COMMON_ZONE_AT(1),
  /**
   * ��˿
   */
  eRS_COMMON_ZONE_FANS(2),
  /**
   * �̼�
   */
  eRS_COMMON_ZONE_MERCHANT(3),
  /**
   * ϵͳ
   */
  eRS_COMMON_ZONE_SYS(4),
  /**
   * ����
   */
  eRS_COMMON_ZONE_FRDS(5),
  /**
   * ȡ����ע
   */
  eRS_COMMON_ZONE_CANCELAT(6),
  /**
   * �������б�
   */
  eRS_COMMON_ZONE_BLACKLIST(7),
  /**
   * ����֪ͨ
   */
  eRS_COMMON_ZONE_COND_NOTICE(8),
  /**
   * δ֪����
   */
  eRS_COMMON_ZONE_UNKNOWN(9);

  private final int value;

  eRS_COMMON_ZONE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
