// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_AT_SELLER extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_SELLER_ID = "";

  /**
   * ��ע�̼�
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �̼�id
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String seller_id;

  public PB_AT_SELLER(Long userid, String seller_id) {
    this.userid = userid;
    this.seller_id = seller_id;
  }

  private PB_AT_SELLER(Builder builder) {
    this(builder.userid, builder.seller_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_AT_SELLER)) return false;
    PB_AT_SELLER o = (PB_AT_SELLER) other;
    return equals(userid, o.userid)
        && equals(seller_id, o.seller_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (seller_id != null ? seller_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_AT_SELLER> {

    public Long userid;
    public String seller_id;

    public Builder() {
    }

    public Builder(PB_AT_SELLER message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.seller_id = message.seller_id;
    }

    /**
     * ��ע�̼�
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �̼�id
     */
    public Builder seller_id(String seller_id) {
      this.seller_id = seller_id;
      return this;
    }

    @Override
    public PB_AT_SELLER build() {
      checkRequiredFields();
      return new PB_AT_SELLER(this);
    }
  }
}
