// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ��ע�����ظ�
 */
public final class PB_ATTENTION_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final String DEFAULT_HEADURL = "";
  public static final Long DEFAULT_TIME = 0L;
  public static final Long DEFAULT_MSGID = 0L;
  public static final String DEFAULT_ACCOUNT = "";
  public static final Long DEFAULT_PRETTYNUM = 0L;
  public static final eRS_COMMON_Ret DEFAULT_ATRET = eRS_COMMON_Ret.eRS_COMMON_SUC;

  /**
   * ��ע������id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ��ע������
   */
  @ProtoField(tag = 2, type = STRING)
  public final String nickname;

  /**
   * ��ע������ͷ��
   */
  @ProtoField(tag = 3, type = STRING)
  public final String headurl;

  /**
   * ʱ��
   */
  @ProtoField(tag = 4, type = INT64)
  public final Long time;

  /**
   * ��ע��msgid
   */
  @ProtoField(tag = 5, type = INT64)
  public final Long msgid;

  /**
   * ��ע�������˺�
   */
  @ProtoField(tag = 6, type = STRING)
  public final String account;

  /**
   * ����
   */
  @ProtoField(tag = 7, type = INT64)
  public final Long prettynum;

  /**
   * �������
   */
  @ProtoField(tag = 8, type = ENUM)
  public final eRS_COMMON_Ret atRet;

  public PB_ATTENTION_REP(Long userid, String nickname, String headurl, Long time, Long msgid, String account, Long prettynum, eRS_COMMON_Ret atRet) {
    this.userid = userid;
    this.nickname = nickname;
    this.headurl = headurl;
    this.time = time;
    this.msgid = msgid;
    this.account = account;
    this.prettynum = prettynum;
    this.atRet = atRet;
  }

  private PB_ATTENTION_REP(Builder builder) {
    this(builder.userid, builder.nickname, builder.headurl, builder.time, builder.msgid, builder.account, builder.prettynum, builder.atRet);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ATTENTION_REP)) return false;
    PB_ATTENTION_REP o = (PB_ATTENTION_REP) other;
    return equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(headurl, o.headurl)
        && equals(time, o.time)
        && equals(msgid, o.msgid)
        && equals(account, o.account)
        && equals(prettynum, o.prettynum)
        && equals(atRet, o.atRet);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (headurl != null ? headurl.hashCode() : 0);
      result = result * 37 + (time != null ? time.hashCode() : 0);
      result = result * 37 + (msgid != null ? msgid.hashCode() : 0);
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (prettynum != null ? prettynum.hashCode() : 0);
      result = result * 37 + (atRet != null ? atRet.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ATTENTION_REP> {

    public Long userid;
    public String nickname;
    public String headurl;
    public Long time;
    public Long msgid;
    public String account;
    public Long prettynum;
    public eRS_COMMON_Ret atRet;

    public Builder() {
    }

    public Builder(PB_ATTENTION_REP message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.headurl = message.headurl;
      this.time = message.time;
      this.msgid = message.msgid;
      this.account = message.account;
      this.prettynum = message.prettynum;
      this.atRet = message.atRet;
    }

    /**
     * ��ע������id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ��ע������
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * ��ע������ͷ��
     */
    public Builder headurl(String headurl) {
      this.headurl = headurl;
      return this;
    }

    /**
     * ʱ��
     */
    public Builder time(Long time) {
      this.time = time;
      return this;
    }

    /**
     * ��ע��msgid
     */
    public Builder msgid(Long msgid) {
      this.msgid = msgid;
      return this;
    }

    /**
     * ��ע�������˺�
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * ����
     */
    public Builder prettynum(Long prettynum) {
      this.prettynum = prettynum;
      return this;
    }

    /**
     * �������
     */
    public Builder atRet(eRS_COMMON_Ret atRet) {
      this.atRet = atRet;
      return this;
    }

    @Override
    public PB_ATTENTION_REP build() {
      checkRequiredFields();
      return new PB_ATTENTION_REP(this);
    }
  }
}
