// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_ACTIVITY_LIST extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_SELLERID = "";
  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;
  public static final List<PB_ACTIVITY> DEFAULT_ACT_LIST = Collections.emptyList();
  public static final Boolean DEFAULT_IS_END = false;

  /**
   * ��б�
   * �̼�id
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String sellerid;

  /**
   * ����
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  /**
   * �̼һ�б����Ϣ�б�
   */
  @ProtoField(tag = 3, label = REPEATED, messageType = PB_ACTIVITY.class)
  public final List<PB_ACTIVITY> act_list;

  /**
   * �Ƿ������һ����
   */
  @ProtoField(tag = 4, type = BOOL)
  public final Boolean is_end;

  public PB_ACTIVITY_LIST(String sellerid, eRS_COMMON_ZONE zone, List<PB_ACTIVITY> act_list, Boolean is_end) {
    this.sellerid = sellerid;
    this.zone = zone;
    this.act_list = immutableCopyOf(act_list);
    this.is_end = is_end;
  }

  private PB_ACTIVITY_LIST(Builder builder) {
    this(builder.sellerid, builder.zone, builder.act_list, builder.is_end);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ACTIVITY_LIST)) return false;
    PB_ACTIVITY_LIST o = (PB_ACTIVITY_LIST) other;
    return equals(sellerid, o.sellerid)
        && equals(zone, o.zone)
        && equals(act_list, o.act_list)
        && equals(is_end, o.is_end);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = sellerid != null ? sellerid.hashCode() : 0;
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      result = result * 37 + (act_list != null ? act_list.hashCode() : 1);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ACTIVITY_LIST> {

    public String sellerid;
    public eRS_COMMON_ZONE zone;
    public List<PB_ACTIVITY> act_list;
    public Boolean is_end;

    public Builder() {
    }

    public Builder(PB_ACTIVITY_LIST message) {
      super(message);
      if (message == null) return;
      this.sellerid = message.sellerid;
      this.zone = message.zone;
      this.act_list = copyOf(message.act_list);
      this.is_end = message.is_end;
    }

    /**
     * ��б�
     * �̼�id
     */
    public Builder sellerid(String sellerid) {
      this.sellerid = sellerid;
      return this;
    }

    /**
     * ����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    /**
     * �̼һ�б����Ϣ�б�
     */
    public Builder act_list(List<PB_ACTIVITY> act_list) {
      this.act_list = checkForNulls(act_list);
      return this;
    }

    /**
     * �Ƿ������һ����
     */
    public Builder is_end(Boolean is_end) {
      this.is_end = is_end;
      return this;
    }

    @Override
    public PB_ACTIVITY_LIST build() {
      checkRequiredFields();
      return new PB_ACTIVITY_LIST(this);
    }
  }
}
