// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_ACTIVITY_RECORD extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_SELLERID = "";
  public static final Integer DEFAULT_BEGINNUM = 0;
  public static final Integer DEFAULT_ACTIVITY_CNTS = 0;
  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;
  public static final Long DEFAULT_USERID = 0L;

  /**
   * ��ȡ���¼
   * �̼�id
   */
  @ProtoField(tag = 1, type = STRING)
  public final String sellerid;

  /**
   * ��ʼ��Ϣ��
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer beginnum;

  /**
   * �����
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer activity_cnts;

  /**
   * ���¼����
   */
  @ProtoField(tag = 4, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  /**
   * �û�id
   */
  @ProtoField(tag = 5, type = INT64, label = REQUIRED)
  public final Long userid;

  public PB_ACTIVITY_RECORD(String sellerid, Integer beginnum, Integer activity_cnts, eRS_COMMON_ZONE zone, Long userid) {
    this.sellerid = sellerid;
    this.beginnum = beginnum;
    this.activity_cnts = activity_cnts;
    this.zone = zone;
    this.userid = userid;
  }

  private PB_ACTIVITY_RECORD(Builder builder) {
    this(builder.sellerid, builder.beginnum, builder.activity_cnts, builder.zone, builder.userid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ACTIVITY_RECORD)) return false;
    PB_ACTIVITY_RECORD o = (PB_ACTIVITY_RECORD) other;
    return equals(sellerid, o.sellerid)
        && equals(beginnum, o.beginnum)
        && equals(activity_cnts, o.activity_cnts)
        && equals(zone, o.zone)
        && equals(userid, o.userid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = sellerid != null ? sellerid.hashCode() : 0;
      result = result * 37 + (beginnum != null ? beginnum.hashCode() : 0);
      result = result * 37 + (activity_cnts != null ? activity_cnts.hashCode() : 0);
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ACTIVITY_RECORD> {

    public String sellerid;
    public Integer beginnum;
    public Integer activity_cnts;
    public eRS_COMMON_ZONE zone;
    public Long userid;

    public Builder() {
    }

    public Builder(PB_ACTIVITY_RECORD message) {
      super(message);
      if (message == null) return;
      this.sellerid = message.sellerid;
      this.beginnum = message.beginnum;
      this.activity_cnts = message.activity_cnts;
      this.zone = message.zone;
      this.userid = message.userid;
    }

    /**
     * ��ȡ���¼
     * �̼�id
     */
    public Builder sellerid(String sellerid) {
      this.sellerid = sellerid;
      return this;
    }

    /**
     * ��ʼ��Ϣ��
     */
    public Builder beginnum(Integer beginnum) {
      this.beginnum = beginnum;
      return this;
    }

    /**
     * �����
     */
    public Builder activity_cnts(Integer activity_cnts) {
      this.activity_cnts = activity_cnts;
      return this;
    }

    /**
     * ���¼����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    @Override
    public PB_ACTIVITY_RECORD build() {
      checkRequiredFields();
      return new PB_ACTIVITY_RECORD(this);
    }
  }
}
