// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_ACTIVITY_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_SELLERID = 0L;
  public static final Long DEFAULT_SENDTIME = 0L;
  public static final Long DEFAULT_MSGID = 0L;
  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;
  public static final eRS_COMMON_Ret DEFAULT_RET = eRS_COMMON_Ret.eRS_COMMON_SUC;

  /**
   * �������ϵͳ��Ϣ�ظ�
   * �̼�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long sellerid;

  /**
   * ����ʱ��
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long sendtime;

  /**
   * �ɹ�ʱ��Ϣid
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long msgid;

  /**
   * �ظ�����
   */
  @ProtoField(tag = 4, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  /**
   * �ɹ�����ʧ��
   */
  @ProtoField(tag = 5, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_Ret ret;

  public PB_ACTIVITY_REP(Long sellerid, Long sendtime, Long msgid, eRS_COMMON_ZONE zone, eRS_COMMON_Ret ret) {
    this.sellerid = sellerid;
    this.sendtime = sendtime;
    this.msgid = msgid;
    this.zone = zone;
    this.ret = ret;
  }

  private PB_ACTIVITY_REP(Builder builder) {
    this(builder.sellerid, builder.sendtime, builder.msgid, builder.zone, builder.ret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ACTIVITY_REP)) return false;
    PB_ACTIVITY_REP o = (PB_ACTIVITY_REP) other;
    return equals(sellerid, o.sellerid)
        && equals(sendtime, o.sendtime)
        && equals(msgid, o.msgid)
        && equals(zone, o.zone)
        && equals(ret, o.ret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = sellerid != null ? sellerid.hashCode() : 0;
      result = result * 37 + (sendtime != null ? sendtime.hashCode() : 0);
      result = result * 37 + (msgid != null ? msgid.hashCode() : 0);
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      result = result * 37 + (ret != null ? ret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ACTIVITY_REP> {

    public Long sellerid;
    public Long sendtime;
    public Long msgid;
    public eRS_COMMON_ZONE zone;
    public eRS_COMMON_Ret ret;

    public Builder() {
    }

    public Builder(PB_ACTIVITY_REP message) {
      super(message);
      if (message == null) return;
      this.sellerid = message.sellerid;
      this.sendtime = message.sendtime;
      this.msgid = message.msgid;
      this.zone = message.zone;
      this.ret = message.ret;
    }

    /**
     * �������ϵͳ��Ϣ�ظ�
     * �̼�id
     */
    public Builder sellerid(Long sellerid) {
      this.sellerid = sellerid;
      return this;
    }

    /**
     * ����ʱ��
     */
    public Builder sendtime(Long sendtime) {
      this.sendtime = sendtime;
      return this;
    }

    /**
     * �ɹ�ʱ��Ϣid
     */
    public Builder msgid(Long msgid) {
      this.msgid = msgid;
      return this;
    }

    /**
     * �ظ�����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    /**
     * �ɹ�����ʧ��
     */
    public Builder ret(eRS_COMMON_Ret ret) {
      this.ret = ret;
      return this;
    }

    @Override
    public PB_ACTIVITY_REP build() {
      checkRequiredFields();
      return new PB_ACTIVITY_REP(this);
    }
  }
}
