// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ����������Ա
 */
public final class PB_ADD_TG_MEMBERS extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_TGID = 0L;
  public static final List<Long> DEFAULT_LIST_MEMBER = Collections.emptyList();

  /**
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ����id
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * ������id
   */
  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * ��ӵĳ�Ա�б�
   */
  @ProtoField(tag = 4, type = INT64, label = REPEATED)
  public final List<Long> list_member;

  public PB_ADD_TG_MEMBERS(Long userid, Integer roomid, Long tgid, List<Long> list_member) {
    this.userid = userid;
    this.roomid = roomid;
    this.tgid = tgid;
    this.list_member = immutableCopyOf(list_member);
  }

  private PB_ADD_TG_MEMBERS(Builder builder) {
    this(builder.userid, builder.roomid, builder.tgid, builder.list_member);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ADD_TG_MEMBERS)) return false;
    PB_ADD_TG_MEMBERS o = (PB_ADD_TG_MEMBERS) other;
    return equals(userid, o.userid)
        && equals(roomid, o.roomid)
        && equals(tgid, o.tgid)
        && equals(list_member, o.list_member);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      result = result * 37 + (tgid != null ? tgid.hashCode() : 0);
      result = result * 37 + (list_member != null ? list_member.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ADD_TG_MEMBERS> {

    public Long userid;
    public Integer roomid;
    public Long tgid;
    public List<Long> list_member;

    public Builder() {
    }

    public Builder(PB_ADD_TG_MEMBERS message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.roomid = message.roomid;
      this.tgid = message.tgid;
      this.list_member = copyOf(message.list_member);
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ����id
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ������id
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * ��ӵĳ�Ա�б�
     */
    public Builder list_member(List<Long> list_member) {
      this.list_member = checkForNulls(list_member);
      return this;
    }

    @Override
    public PB_ADD_TG_MEMBERS build() {
      checkRequiredFields();
      return new PB_ADD_TG_MEMBERS(this);
    }
  }
}
