// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ����������Ա�ظ�
 */
public final class PB_ADD_TG_MEMBERS_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final eRS_ADD_TG_MEMBERS_Ret DEFAULT_RET = eRS_ADD_TG_MEMBERS_Ret.eRS_ADD_TG_SUC;
  public static final Long DEFAULT_TGID = 0L;
  public static final List<PB_USER> DEFAULT_USER_LIST = Collections.emptyList();
  public static final Boolean DEFAULT_IS_END = false;

  /**
   * ������û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ������س�
   */
  @ProtoField(tag = 2, type = STRING)
  public final String nickname;

  /**
   * ��ӽ��
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_ADD_TG_MEMBERS_Ret ret;

  /**
   * ������id
   */
  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * �û��б�
   */
  @ProtoField(tag = 5, label = REPEATED, messageType = PB_USER.class)
  public final List<PB_USER> user_list;

  /**
   * �Ƿ������һ����
   */
  @ProtoField(tag = 6, type = BOOL)
  public final Boolean is_end;

  public PB_ADD_TG_MEMBERS_REP(Long userid, String nickname, eRS_ADD_TG_MEMBERS_Ret ret, Long tgid, List<PB_USER> user_list, Boolean is_end) {
    this.userid = userid;
    this.nickname = nickname;
    this.ret = ret;
    this.tgid = tgid;
    this.user_list = immutableCopyOf(user_list);
    this.is_end = is_end;
  }

  private PB_ADD_TG_MEMBERS_REP(Builder builder) {
    this(builder.userid, builder.nickname, builder.ret, builder.tgid, builder.user_list, builder.is_end);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ADD_TG_MEMBERS_REP)) return false;
    PB_ADD_TG_MEMBERS_REP o = (PB_ADD_TG_MEMBERS_REP) other;
    return equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(ret, o.ret)
        && equals(tgid, o.tgid)
        && equals(user_list, o.user_list)
        && equals(is_end, o.is_end);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (ret != null ? ret.hashCode() : 0);
      result = result * 37 + (tgid != null ? tgid.hashCode() : 0);
      result = result * 37 + (user_list != null ? user_list.hashCode() : 1);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ADD_TG_MEMBERS_REP> {

    public Long userid;
    public String nickname;
    public eRS_ADD_TG_MEMBERS_Ret ret;
    public Long tgid;
    public List<PB_USER> user_list;
    public Boolean is_end;

    public Builder() {
    }

    public Builder(PB_ADD_TG_MEMBERS_REP message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.ret = message.ret;
      this.tgid = message.tgid;
      this.user_list = copyOf(message.user_list);
      this.is_end = message.is_end;
    }

    /**
     * ������û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ������س�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * ��ӽ��
     */
    public Builder ret(eRS_ADD_TG_MEMBERS_Ret ret) {
      this.ret = ret;
      return this;
    }

    /**
     * ������id
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * �û��б�
     */
    public Builder user_list(List<PB_USER> user_list) {
      this.user_list = checkForNulls(user_list);
      return this;
    }

    /**
     * �Ƿ������һ����
     */
    public Builder is_end(Boolean is_end) {
      this.is_end = is_end;
      return this;
    }

    @Override
    public PB_ADD_TG_MEMBERS_REP build() {
      checkRequiredFields();
      return new PB_ADD_TG_MEMBERS_REP(this);
    }
  }
}
