// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ���������û���Ϣ
 */
public final class PB_AFAMQ_INFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_APPLYID = 0;
  public static final Integer DEFAULT_APPLYTIME = 0;

  /**
   * ������Ϣid
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer applyid;

  /**
   * ��Ϣ
   */
  @ProtoField(tag = 2, label = REQUIRED)
  public final PB_USER user;

  /**
   * ����ʱ�� add by zm 2015/9/7
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer applytime;

  public PB_AFAMQ_INFO(Integer applyid, PB_USER user, Integer applytime) {
    this.applyid = applyid;
    this.user = user;
    this.applytime = applytime;
  }

  private PB_AFAMQ_INFO(Builder builder) {
    this(builder.applyid, builder.user, builder.applytime);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_AFAMQ_INFO)) return false;
    PB_AFAMQ_INFO o = (PB_AFAMQ_INFO) other;
    return equals(applyid, o.applyid)
        && equals(user, o.user)
        && equals(applytime, o.applytime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = applyid != null ? applyid.hashCode() : 0;
      result = result * 37 + (user != null ? user.hashCode() : 0);
      result = result * 37 + (applytime != null ? applytime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_AFAMQ_INFO> {

    public Integer applyid;
    public PB_USER user;
    public Integer applytime;

    public Builder() {
    }

    public Builder(PB_AFAMQ_INFO message) {
      super(message);
      if (message == null) return;
      this.applyid = message.applyid;
      this.user = message.user;
      this.applytime = message.applytime;
    }

    /**
     * ������Ϣid
     */
    public Builder applyid(Integer applyid) {
      this.applyid = applyid;
      return this;
    }

    /**
     * ��Ϣ
     */
    public Builder user(PB_USER user) {
      this.user = user;
      return this;
    }

    /**
     * ����ʱ�� add by zm 2015/9/7
     */
    public Builder applytime(Integer applytime) {
      this.applytime = applytime;
      return this;
    }

    @Override
    public PB_AFAMQ_INFO build() {
      checkRequiredFields();
      return new PB_AFAMQ_INFO(this);
    }
  }
}
