// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\commonMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �Զ����������
 */
public final class PB_COM_CUSTOM_ERROR extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ERRORCODE = 0;
  public static final String DEFAULT_ERRORTXT = "";
  public static final Integer DEFAULT_CTRLCODE = 0;

  /**
   * ������
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer errorCode;

  /**
   * ��������
   */
  @ProtoField(tag = 2, type = STRING)
  public final String errorTxt;

  /**
   * ������ �����ڴ��������
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer ctrlCode;

  public PB_COM_CUSTOM_ERROR(Integer errorCode, String errorTxt, Integer ctrlCode) {
    this.errorCode = errorCode;
    this.errorTxt = errorTxt;
    this.ctrlCode = ctrlCode;
  }

  private PB_COM_CUSTOM_ERROR(Builder builder) {
    this(builder.errorCode, builder.errorTxt, builder.ctrlCode);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_COM_CUSTOM_ERROR)) return false;
    PB_COM_CUSTOM_ERROR o = (PB_COM_CUSTOM_ERROR) other;
    return equals(errorCode, o.errorCode)
        && equals(errorTxt, o.errorTxt)
        && equals(ctrlCode, o.ctrlCode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = errorCode != null ? errorCode.hashCode() : 0;
      result = result * 37 + (errorTxt != null ? errorTxt.hashCode() : 0);
      result = result * 37 + (ctrlCode != null ? ctrlCode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_COM_CUSTOM_ERROR> {

    public Integer errorCode;
    public String errorTxt;
    public Integer ctrlCode;

    public Builder() {
    }

    public Builder(PB_COM_CUSTOM_ERROR message) {
      super(message);
      if (message == null) return;
      this.errorCode = message.errorCode;
      this.errorTxt = message.errorTxt;
      this.ctrlCode = message.ctrlCode;
    }

    /**
     * ������
     */
    public Builder errorCode(Integer errorCode) {
      this.errorCode = errorCode;
      return this;
    }

    /**
     * ��������
     */
    public Builder errorTxt(String errorTxt) {
      this.errorTxt = errorTxt;
      return this;
    }

    /**
     * ������ �����ڴ��������
     */
    public Builder ctrlCode(Integer ctrlCode) {
      this.ctrlCode = ctrlCode;
      return this;
    }

    @Override
    public PB_COM_CUSTOM_ERROR build() {
      checkRequiredFields();
      return new PB_COM_CUSTOM_ERROR(this);
    }
  }
}
