// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ȡ����ע�ظ�
 */
public final class PB_CANCEL_AT_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_PEERID = 0L;
  public static final Integer DEFAULT_ZONE = 0;
  public static final String DEFAULT_ACCOUNT = "";
  public static final String DEFAULT_NICKNAME = "";
  public static final String DEFAULT_HEADURL = "";
  public static final eRS_COMMON_Ret DEFAULT_RET = eRS_COMMON_Ret.eRS_COMMON_SUC;

  /**
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ��ȡ���û�id
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long peerid;

  /**
   * ����
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer zone;

  /**
   * �˺�
   */
  @ProtoField(tag = 4, type = STRING)
  public final String account;

  /**
   * �û���
   */
  @ProtoField(tag = 5, type = STRING)
  public final String nickname;

  /**
   * ͷ��
   */
  @ProtoField(tag = 6, type = STRING)
  public final String headurl;

  /**
   * ����ֵ
   */
  @ProtoField(tag = 7, type = ENUM)
  public final eRS_COMMON_Ret ret;

  public PB_CANCEL_AT_REP(Long userid, Long peerid, Integer zone, String account, String nickname, String headurl, eRS_COMMON_Ret ret) {
    this.userid = userid;
    this.peerid = peerid;
    this.zone = zone;
    this.account = account;
    this.nickname = nickname;
    this.headurl = headurl;
    this.ret = ret;
  }

  private PB_CANCEL_AT_REP(Builder builder) {
    this(builder.userid, builder.peerid, builder.zone, builder.account, builder.nickname, builder.headurl, builder.ret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_CANCEL_AT_REP)) return false;
    PB_CANCEL_AT_REP o = (PB_CANCEL_AT_REP) other;
    return equals(userid, o.userid)
        && equals(peerid, o.peerid)
        && equals(zone, o.zone)
        && equals(account, o.account)
        && equals(nickname, o.nickname)
        && equals(headurl, o.headurl)
        && equals(ret, o.ret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (peerid != null ? peerid.hashCode() : 0);
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (headurl != null ? headurl.hashCode() : 0);
      result = result * 37 + (ret != null ? ret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_CANCEL_AT_REP> {

    public Long userid;
    public Long peerid;
    public Integer zone;
    public String account;
    public String nickname;
    public String headurl;
    public eRS_COMMON_Ret ret;

    public Builder() {
    }

    public Builder(PB_CANCEL_AT_REP message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.peerid = message.peerid;
      this.zone = message.zone;
      this.account = message.account;
      this.nickname = message.nickname;
      this.headurl = message.headurl;
      this.ret = message.ret;
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ��ȡ���û�id
     */
    public Builder peerid(Long peerid) {
      this.peerid = peerid;
      return this;
    }

    /**
     * ����
     */
    public Builder zone(Integer zone) {
      this.zone = zone;
      return this;
    }

    /**
     * �˺�
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * �û���
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * ͷ��
     */
    public Builder headurl(String headurl) {
      this.headurl = headurl;
      return this;
    }

    /**
     * ����ֵ
     */
    public Builder ret(eRS_COMMON_Ret ret) {
      this.ret = ret;
      return this;
    }

    @Override
    public PB_CANCEL_AT_REP build() {
      checkRequiredFields();
      return new PB_CANCEL_AT_REP(this);
    }
  }
}
