// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �û�״̬
 */
public final class PB_CLIENT_STATUS extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final eRS_USER_AT DEFAULT_ATVIEW = eRS_USER_AT.USER_AT_APP;
  public static final Long DEFAULT_TARGETID = 0L;

  /**
   * room id
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * userid
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �û���ǰ����
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_USER_AT atview;

  /**
   * Ŀ��ID ���û�ID,����ID,������ID...��
   */
  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long targetid;

  public PB_CLIENT_STATUS(Integer roomid, Long userid, eRS_USER_AT atview, Long targetid) {
    this.roomid = roomid;
    this.userid = userid;
    this.atview = atview;
    this.targetid = targetid;
  }

  private PB_CLIENT_STATUS(Builder builder) {
    this(builder.roomid, builder.userid, builder.atview, builder.targetid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_CLIENT_STATUS)) return false;
    PB_CLIENT_STATUS o = (PB_CLIENT_STATUS) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(atview, o.atview)
        && equals(targetid, o.targetid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (atview != null ? atview.hashCode() : 0);
      result = result * 37 + (targetid != null ? targetid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_CLIENT_STATUS> {

    public Integer roomid;
    public Long userid;
    public eRS_USER_AT atview;
    public Long targetid;

    public Builder() {
    }

    public Builder(PB_CLIENT_STATUS message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.atview = message.atview;
      this.targetid = message.targetid;
    }

    /**
     * room id
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * userid
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �û���ǰ����
     */
    public Builder atview(eRS_USER_AT atview) {
      this.atview = atview;
      return this;
    }

    /**
     * Ŀ��ID ���û�ID,����ID,������ID...��
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    @Override
    public PB_CLIENT_STATUS build() {
      checkRequiredFields();
      return new PB_CLIENT_STATUS(this);
    }
  }
}
