// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ȡ����ע
 */
public final class PB_CANCEL_AT extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_CANCEL_UID = "";
  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;

  /**
   * ִ���û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �û�account,���̼�id
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String cancel_uid;

  /**
   * ����
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  public PB_CANCEL_AT(Long userid, String cancel_uid, eRS_COMMON_ZONE zone) {
    this.userid = userid;
    this.cancel_uid = cancel_uid;
    this.zone = zone;
  }

  private PB_CANCEL_AT(Builder builder) {
    this(builder.userid, builder.cancel_uid, builder.zone);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_CANCEL_AT)) return false;
    PB_CANCEL_AT o = (PB_CANCEL_AT) other;
    return equals(userid, o.userid)
        && equals(cancel_uid, o.cancel_uid)
        && equals(zone, o.zone);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (cancel_uid != null ? cancel_uid.hashCode() : 0);
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_CANCEL_AT> {

    public Long userid;
    public String cancel_uid;
    public eRS_COMMON_ZONE zone;

    public Builder() {
    }

    public Builder(PB_CANCEL_AT message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.cancel_uid = message.cancel_uid;
      this.zone = message.zone;
    }

    /**
     * ִ���û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �û�account,���̼�id
     */
    public Builder cancel_uid(String cancel_uid) {
      this.cancel_uid = cancel_uid;
      return this;
    }

    /**
     * ����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    @Override
    public PB_CANCEL_AT build() {
      checkRequiredFields();
      return new PB_CANCEL_AT(this);
    }
  }
}
