// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ��������֪ͨ
 */
public final class PB_CREATE_FAMILY_NOTICE extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  public PB_CREATE_FAMILY_NOTICE(Integer roomid) {
    this.roomid = roomid;
  }

  private PB_CREATE_FAMILY_NOTICE(Builder builder) {
    this(builder.roomid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_CREATE_FAMILY_NOTICE)) return false;
    return equals(roomid, ((PB_CREATE_FAMILY_NOTICE) other).roomid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = roomid != null ? roomid.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<PB_CREATE_FAMILY_NOTICE> {

    public Integer roomid;

    public Builder() {
    }

    public Builder(PB_CREATE_FAMILY_NOTICE message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
    }

    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    @Override
    public PB_CREATE_FAMILY_NOTICE build() {
      checkRequiredFields();
      return new PB_CREATE_FAMILY_NOTICE(this);
    }
  }
}
