// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * chat message
 */
public final class PB_CHAT_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final Integer DEFAULT_MSG_INDEX = 0;
  public static final ePB_CHAT_ZONE DEFAULT_CHATZONE = ePB_CHAT_ZONE.CM_ZONE_FAM_NORMAL;
  public static final Long DEFAULT_TARGETID = 0L;

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * �û�ID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �ͻ�����Ϣ���
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer msg_index;

  /**
   * ��������
   */
  @ProtoField(tag = 4, type = ENUM, label = REQUIRED)
  public final ePB_CHAT_ZONE chatzone;

  /**
   * Ŀ��ID���û�ID,����ID,������ID...)
   */
  @ProtoField(tag = 5, type = INT64, label = REQUIRED)
  public final Long targetid;

  /**
   * ��Ϣ����
   */
  @ProtoField(tag = 6)
  public final PB_MESSAGE msg_data;

  /**
   * ������
   */
  @ProtoField(tag = 7)
  public final PB_USER from_user;

  /**
   * ������
   */
  @ProtoField(tag = 8)
  public final PB_USER to_user;

  public PB_CHAT_MSG(Integer roomid, Long userid, Integer msg_index, ePB_CHAT_ZONE chatzone, Long targetid, PB_MESSAGE msg_data, PB_USER from_user, PB_USER to_user) {
    this.roomid = roomid;
    this.userid = userid;
    this.msg_index = msg_index;
    this.chatzone = chatzone;
    this.targetid = targetid;
    this.msg_data = msg_data;
    this.from_user = from_user;
    this.to_user = to_user;
  }

  private PB_CHAT_MSG(Builder builder) {
    this(builder.roomid, builder.userid, builder.msg_index, builder.chatzone, builder.targetid, builder.msg_data, builder.from_user, builder.to_user);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_CHAT_MSG)) return false;
    PB_CHAT_MSG o = (PB_CHAT_MSG) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(msg_index, o.msg_index)
        && equals(chatzone, o.chatzone)
        && equals(targetid, o.targetid)
        && equals(msg_data, o.msg_data)
        && equals(from_user, o.from_user)
        && equals(to_user, o.to_user);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (msg_index != null ? msg_index.hashCode() : 0);
      result = result * 37 + (chatzone != null ? chatzone.hashCode() : 0);
      result = result * 37 + (targetid != null ? targetid.hashCode() : 0);
      result = result * 37 + (msg_data != null ? msg_data.hashCode() : 0);
      result = result * 37 + (from_user != null ? from_user.hashCode() : 0);
      result = result * 37 + (to_user != null ? to_user.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_CHAT_MSG> {

    public Integer roomid;
    public Long userid;
    public Integer msg_index;
    public ePB_CHAT_ZONE chatzone;
    public Long targetid;
    public PB_MESSAGE msg_data;
    public PB_USER from_user;
    public PB_USER to_user;

    public Builder() {
    }

    public Builder(PB_CHAT_MSG message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.msg_index = message.msg_index;
      this.chatzone = message.chatzone;
      this.targetid = message.targetid;
      this.msg_data = message.msg_data;
      this.from_user = message.from_user;
      this.to_user = message.to_user;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * �û�ID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �ͻ�����Ϣ���
     */
    public Builder msg_index(Integer msg_index) {
      this.msg_index = msg_index;
      return this;
    }

    /**
     * ��������
     */
    public Builder chatzone(ePB_CHAT_ZONE chatzone) {
      this.chatzone = chatzone;
      return this;
    }

    /**
     * Ŀ��ID���û�ID,����ID,������ID...)
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    /**
     * ��Ϣ����
     */
    public Builder msg_data(PB_MESSAGE msg_data) {
      this.msg_data = msg_data;
      return this;
    }

    /**
     * ������
     */
    public Builder from_user(PB_USER from_user) {
      this.from_user = from_user;
      return this;
    }

    /**
     * ������
     */
    public Builder to_user(PB_USER to_user) {
      this.to_user = to_user;
      return this;
    }

    @Override
    public PB_CHAT_MSG build() {
      checkRequiredFields();
      return new PB_CHAT_MSG(this);
    }
  }
}
