// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * phone client login room svr
 */
public final class PB_CLIENT_ENTERROOM_DATA extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final Integer DEFAULT_ROOMID = 0;
  public static final Integer DEFAULT_LOGINROOMKEY = 0;
  public static final String DEFAULT_USERTOKEN = "";
  public static final Boolean DEFAULT_FIRSTLOGIN = false;

  /**
   * pg uid
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * chat room id
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * chat enter room key
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer loginroomkey;

  /**
   * user token
   */
  @ProtoField(tag = 4, type = STRING)
  public final String usertoken;

  @ProtoField(tag = 5, type = BOOL)
  public final Boolean firstlogin;

  public PB_CLIENT_ENTERROOM_DATA(Long userid, Integer roomid, Integer loginroomkey, String usertoken, Boolean firstlogin) {
    this.userid = userid;
    this.roomid = roomid;
    this.loginroomkey = loginroomkey;
    this.usertoken = usertoken;
    this.firstlogin = firstlogin;
  }

  private PB_CLIENT_ENTERROOM_DATA(Builder builder) {
    this(builder.userid, builder.roomid, builder.loginroomkey, builder.usertoken, builder.firstlogin);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_CLIENT_ENTERROOM_DATA)) return false;
    PB_CLIENT_ENTERROOM_DATA o = (PB_CLIENT_ENTERROOM_DATA) other;
    return equals(userid, o.userid)
        && equals(roomid, o.roomid)
        && equals(loginroomkey, o.loginroomkey)
        && equals(usertoken, o.usertoken)
        && equals(firstlogin, o.firstlogin);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      result = result * 37 + (loginroomkey != null ? loginroomkey.hashCode() : 0);
      result = result * 37 + (usertoken != null ? usertoken.hashCode() : 0);
      result = result * 37 + (firstlogin != null ? firstlogin.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_CLIENT_ENTERROOM_DATA> {

    public Long userid;
    public Integer roomid;
    public Integer loginroomkey;
    public String usertoken;
    public Boolean firstlogin;

    public Builder() {
    }

    public Builder(PB_CLIENT_ENTERROOM_DATA message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.roomid = message.roomid;
      this.loginroomkey = message.loginroomkey;
      this.usertoken = message.usertoken;
      this.firstlogin = message.firstlogin;
    }

    /**
     * pg uid
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * chat room id
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * chat enter room key
     */
    public Builder loginroomkey(Integer loginroomkey) {
      this.loginroomkey = loginroomkey;
      return this;
    }

    /**
     * user token
     */
    public Builder usertoken(String usertoken) {
      this.usertoken = usertoken;
      return this;
    }

    public Builder firstlogin(Boolean firstlogin) {
      this.firstlogin = firstlogin;
      return this;
    }

    @Override
    public PB_CLIENT_ENTERROOM_DATA build() {
      checkRequiredFields();
      return new PB_CLIENT_ENTERROOM_DATA(this);
    }
  }
}
