// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs(15).proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ɾ����Ϣ��ʷ��¼
 */
public final class PB_DEL_HISTORY_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;
  public static final Long DEFAULT_MSGID = 0L;

  /**
   * Ҫɾ������Ϣ����
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  /**
   * Ҫɾ������Ϣ��
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long msgid;

  public PB_DEL_HISTORY_MSG(eRS_COMMON_ZONE zone, Long msgid) {
    this.zone = zone;
    this.msgid = msgid;
  }

  private PB_DEL_HISTORY_MSG(Builder builder) {
    this(builder.zone, builder.msgid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_DEL_HISTORY_MSG)) return false;
    PB_DEL_HISTORY_MSG o = (PB_DEL_HISTORY_MSG) other;
    return equals(zone, o.zone)
        && equals(msgid, o.msgid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = zone != null ? zone.hashCode() : 0;
      result = result * 37 + (msgid != null ? msgid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_DEL_HISTORY_MSG> {

    public eRS_COMMON_ZONE zone;
    public Long msgid;

    public Builder() {
    }

    public Builder(PB_DEL_HISTORY_MSG message) {
      super(message);
      if (message == null) return;
      this.zone = message.zone;
      this.msgid = message.msgid;
    }

    /**
     * Ҫɾ������Ϣ����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    /**
     * Ҫɾ������Ϣ��
     */
    public Builder msgid(Long msgid) {
      this.msgid = msgid;
      return this;
    }

    @Override
    public PB_DEL_HISTORY_MSG build() {
      checkRequiredFields();
      return new PB_DEL_HISTORY_MSG(this);
    }
  }
}
