// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �û��˳��������Ա��Ϣ
 */
public final class PB_EXIT_TALKGROUP_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_TGID = 0L;

  /**
   * ������ID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * �˳����û���Ϣ
   */
  @ProtoField(tag = 2, label = REQUIRED)
  public final PB_USER user;

  public PB_EXIT_TALKGROUP_MSG(Long tgid, PB_USER user) {
    this.tgid = tgid;
    this.user = user;
  }

  private PB_EXIT_TALKGROUP_MSG(Builder builder) {
    this(builder.tgid, builder.user);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_EXIT_TALKGROUP_MSG)) return false;
    PB_EXIT_TALKGROUP_MSG o = (PB_EXIT_TALKGROUP_MSG) other;
    return equals(tgid, o.tgid)
        && equals(user, o.user);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = tgid != null ? tgid.hashCode() : 0;
      result = result * 37 + (user != null ? user.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_EXIT_TALKGROUP_MSG> {

    public Long tgid;
    public PB_USER user;

    public Builder() {
    }

    public Builder(PB_EXIT_TALKGROUP_MSG message) {
      super(message);
      if (message == null) return;
      this.tgid = message.tgid;
      this.user = message.user;
    }

    /**
     * ������ID
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * �˳����û���Ϣ
     */
    public Builder user(PB_USER user) {
      this.user = user;
      return this;
    }

    @Override
    public PB_EXIT_TALKGROUP_MSG build() {
      checkRequiredFields();
      return new PB_EXIT_TALKGROUP_MSG(this);
    }
  }
}
