// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������Ϣ
 */
public final class PB_FRIEND_ITEM extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final String DEFAULT_HEAD = "";
  public static final String DEFAULT_APPACCOUNT = "";
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final Long DEFAULT_PRETTYNUM = 0L;
  public static final Integer DEFAULT_LEVEL = 0;
  public static final Integer DEFAULT_VIP = 0;

  /**
   * ID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �ǳ�
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String nickname;

  /**
   * ͷ��
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String head;

  /**
   * �û�ƽ̨�˺�
   */
  @ProtoField(tag = 4, type = STRING)
  public final String appaccount;

  /**
   * ����id
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer familyid;

  /**
   * ����
   */
  @ProtoField(tag = 6, type = INT64)
  public final Long prettynum;

  /**
   * �ȼ�
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer level;

  /**
   * VIP
   */
  @ProtoField(tag = 8, type = INT32)
  public final Integer vip;

  public PB_FRIEND_ITEM(Long userid, String nickname, String head, String appaccount, Integer familyid, Long prettynum, Integer level, Integer vip) {
    this.userid = userid;
    this.nickname = nickname;
    this.head = head;
    this.appaccount = appaccount;
    this.familyid = familyid;
    this.prettynum = prettynum;
    this.level = level;
    this.vip = vip;
  }

  private PB_FRIEND_ITEM(Builder builder) {
    this(builder.userid, builder.nickname, builder.head, builder.appaccount, builder.familyid, builder.prettynum, builder.level, builder.vip);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_FRIEND_ITEM)) return false;
    PB_FRIEND_ITEM o = (PB_FRIEND_ITEM) other;
    return equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(head, o.head)
        && equals(appaccount, o.appaccount)
        && equals(familyid, o.familyid)
        && equals(prettynum, o.prettynum)
        && equals(level, o.level)
        && equals(vip, o.vip);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (head != null ? head.hashCode() : 0);
      result = result * 37 + (appaccount != null ? appaccount.hashCode() : 0);
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (prettynum != null ? prettynum.hashCode() : 0);
      result = result * 37 + (level != null ? level.hashCode() : 0);
      result = result * 37 + (vip != null ? vip.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_FRIEND_ITEM> {

    public Long userid;
    public String nickname;
    public String head;
    public String appaccount;
    public Integer familyid;
    public Long prettynum;
    public Integer level;
    public Integer vip;

    public Builder() {
    }

    public Builder(PB_FRIEND_ITEM message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.head = message.head;
      this.appaccount = message.appaccount;
      this.familyid = message.familyid;
      this.prettynum = message.prettynum;
      this.level = message.level;
      this.vip = message.vip;
    }

    /**
     * ID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �ǳ�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * ͷ��
     */
    public Builder head(String head) {
      this.head = head;
      return this;
    }

    /**
     * �û�ƽ̨�˺�
     */
    public Builder appaccount(String appaccount) {
      this.appaccount = appaccount;
      return this;
    }

    /**
     * ����id
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * ����
     */
    public Builder prettynum(Long prettynum) {
      this.prettynum = prettynum;
      return this;
    }

    /**
     * �ȼ�
     */
    public Builder level(Integer level) {
      this.level = level;
      return this;
    }

    /**
     * VIP
     */
    public Builder vip(Integer vip) {
      this.vip = vip;
      return this;
    }

    @Override
    public PB_FRIEND_ITEM build() {
      checkRequiredFields();
      return new PB_FRIEND_ITEM(this);
    }
  }
}
