// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_FRIEND_DELFRD extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final List<Long> DEFAULT_DEL_USERID = Collections.emptyList();

  /**
   * UID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �ɹ�ɾ���ĺ���UID
   */
  @ProtoField(tag = 2, type = INT64, label = REPEATED)
  public final List<Long> del_userid;

  public PB_FRIEND_DELFRD(Long userid, List<Long> del_userid) {
    this.userid = userid;
    this.del_userid = immutableCopyOf(del_userid);
  }

  private PB_FRIEND_DELFRD(Builder builder) {
    this(builder.userid, builder.del_userid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_FRIEND_DELFRD)) return false;
    PB_FRIEND_DELFRD o = (PB_FRIEND_DELFRD) other;
    return equals(userid, o.userid)
        && equals(del_userid, o.del_userid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (del_userid != null ? del_userid.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_FRIEND_DELFRD> {

    public Long userid;
    public List<Long> del_userid;

    public Builder() {
    }

    public Builder(PB_FRIEND_DELFRD message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.del_userid = copyOf(message.del_userid);
    }

    /**
     * UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �ɹ�ɾ���ĺ���UID
     */
    public Builder del_userid(List<Long> del_userid) {
      this.del_userid = checkForNulls(del_userid);
      return this;
    }

    @Override
    public PB_FRIEND_DELFRD build() {
      checkRequiredFields();
      return new PB_FRIEND_DELFRD(this);
    }
  }
}
