// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;

/**
 * ������Ϣ
 */
public final class PB_FAMILY_MSG_INFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_MSGCNT = 0;
  public static final Long DEFAULT_UNREAD_CNT = 0L;

  /**
   * ����
   */
  @ProtoField(tag = 1)
  public final PB_FAMILY family;

  /**
   * δ����Ϣ��
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer msgcnt;

  /**
   * ���һ����Ϣ
   */
  @ProtoField(tag = 3)
  public final PB_RS_MSG_INFO last_msg;

  /**
   * δ����Ϣ��
   */
  @ProtoField(tag = 4, type = INT64)
  public final Long unread_cnt;

  public PB_FAMILY_MSG_INFO(PB_FAMILY family, Integer msgcnt, PB_RS_MSG_INFO last_msg, Long unread_cnt) {
    this.family = family;
    this.msgcnt = msgcnt;
    this.last_msg = last_msg;
    this.unread_cnt = unread_cnt;
  }

  private PB_FAMILY_MSG_INFO(Builder builder) {
    this(builder.family, builder.msgcnt, builder.last_msg, builder.unread_cnt);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_FAMILY_MSG_INFO)) return false;
    PB_FAMILY_MSG_INFO o = (PB_FAMILY_MSG_INFO) other;
    return equals(family, o.family)
        && equals(msgcnt, o.msgcnt)
        && equals(last_msg, o.last_msg)
        && equals(unread_cnt, o.unread_cnt);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = family != null ? family.hashCode() : 0;
      result = result * 37 + (msgcnt != null ? msgcnt.hashCode() : 0);
      result = result * 37 + (last_msg != null ? last_msg.hashCode() : 0);
      result = result * 37 + (unread_cnt != null ? unread_cnt.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_FAMILY_MSG_INFO> {

    public PB_FAMILY family;
    public Integer msgcnt;
    public PB_RS_MSG_INFO last_msg;
    public Long unread_cnt;

    public Builder() {
    }

    public Builder(PB_FAMILY_MSG_INFO message) {
      super(message);
      if (message == null) return;
      this.family = message.family;
      this.msgcnt = message.msgcnt;
      this.last_msg = message.last_msg;
      this.unread_cnt = message.unread_cnt;
    }

    /**
     * ����
     */
    public Builder family(PB_FAMILY family) {
      this.family = family;
      return this;
    }

    /**
     * δ����Ϣ��
     */
    public Builder msgcnt(Integer msgcnt) {
      this.msgcnt = msgcnt;
      return this;
    }

    /**
     * ���һ����Ϣ
     */
    public Builder last_msg(PB_RS_MSG_INFO last_msg) {
      this.last_msg = last_msg;
      return this;
    }

    /**
     * δ����Ϣ��
     */
    public Builder unread_cnt(Long unread_cnt) {
      this.unread_cnt = unread_cnt;
      return this;
    }

    @Override
    public PB_FAMILY_MSG_INFO build() {
      return new PB_FAMILY_MSG_INFO(this);
    }
  }
}
