// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ���Ѳ�����ɾ��,�Ӻ�������
 */
public final class PB_FRIEND_CTRLUSER extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final List<Long> DEFAULT_TARGET_USERID = Collections.emptyList();

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * ��ҽ�ɫUID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ������������UID
   */
  @ProtoField(tag = 3, type = INT64, label = REPEATED)
  public final List<Long> target_userid;

  public PB_FRIEND_CTRLUSER(Integer roomid, Long userid, List<Long> target_userid) {
    this.roomid = roomid;
    this.userid = userid;
    this.target_userid = immutableCopyOf(target_userid);
  }

  private PB_FRIEND_CTRLUSER(Builder builder) {
    this(builder.roomid, builder.userid, builder.target_userid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_FRIEND_CTRLUSER)) return false;
    PB_FRIEND_CTRLUSER o = (PB_FRIEND_CTRLUSER) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(target_userid, o.target_userid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (target_userid != null ? target_userid.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_FRIEND_CTRLUSER> {

    public Integer roomid;
    public Long userid;
    public List<Long> target_userid;

    public Builder() {
    }

    public Builder(PB_FRIEND_CTRLUSER message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.target_userid = copyOf(message.target_userid);
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ��ҽ�ɫUID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ������������UID
     */
    public Builder target_userid(List<Long> target_userid) {
      this.target_userid = checkForNulls(target_userid);
      return this;
    }

    @Override
    public PB_FRIEND_CTRLUSER build() {
      checkRequiredFields();
      return new PB_FRIEND_CTRLUSER(this);
    }
  }
}
