// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\loginMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_FAMILY_INFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_ISFILL = false;
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final String DEFAULT_FAMILYNAME = "";
  public static final String DEFAULT_FAMILYINTRO = "";
  public static final String DEFAULT_FAMILYURL = "";
  public static final Integer DEFAULT_COIN = 0;
  public static final Integer DEFAULT_PERSONS = 0;
  public static final Integer DEFAULT_MANAGER_NUM = 0;
  public static final String DEFAULT_ALLOCATE_PROFIT = "";
  public static final Integer DEFAULT_FAMILY_LEVEL = 0;
  public static final Boolean DEFAULT_ISALLOW = false;

  /**
   * �Ƿ�Լ�����Ϣ��ֵ��true�м�����Ϣ��false,�޼�����Ϣ
   */
  @ProtoField(tag = 1, type = BOOL, label = REQUIRED)
  public final Boolean isFill;

  /**
   * ����id
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer familyid;

  /**
   * ������
   */
  @ProtoField(tag = 3, type = STRING)
  public final String familyname;

  /**
   * �������
   */
  @ProtoField(tag = 4, type = STRING)
  public final String familyintro;

  /**
   * ����ͷ��
   */
  @ProtoField(tag = 5, type = STRING)
  public final String familyurl;

  /**
   * ������
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer coin;

  /**
   * ��������
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer persons;

  /**
   * ����Ա����
   */
  @ProtoField(tag = 8, type = INT32)
  public final Integer manager_num;

  /**
   * ����ֺ�
   */
  @ProtoField(tag = 9, type = STRING)
  public final String allocate_profit;

  /**
   * ����ȼ�
   */
  @ProtoField(tag = 10, type = INT32)
  public final Integer family_level;

  /**
   * �Ƿ�������ռ���������Ϣ
   */
  @ProtoField(tag = 11, type = BOOL)
  public final Boolean isallow;

  public PB_FAMILY_INFO(Boolean isFill, Integer familyid, String familyname, String familyintro, String familyurl, Integer coin, Integer persons, Integer manager_num, String allocate_profit, Integer family_level, Boolean isallow) {
    this.isFill = isFill;
    this.familyid = familyid;
    this.familyname = familyname;
    this.familyintro = familyintro;
    this.familyurl = familyurl;
    this.coin = coin;
    this.persons = persons;
    this.manager_num = manager_num;
    this.allocate_profit = allocate_profit;
    this.family_level = family_level;
    this.isallow = isallow;
  }

  private PB_FAMILY_INFO(Builder builder) {
    this(builder.isFill, builder.familyid, builder.familyname, builder.familyintro, builder.familyurl, builder.coin, builder.persons, builder.manager_num, builder.allocate_profit, builder.family_level, builder.isallow);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_FAMILY_INFO)) return false;
    PB_FAMILY_INFO o = (PB_FAMILY_INFO) other;
    return equals(isFill, o.isFill)
        && equals(familyid, o.familyid)
        && equals(familyname, o.familyname)
        && equals(familyintro, o.familyintro)
        && equals(familyurl, o.familyurl)
        && equals(coin, o.coin)
        && equals(persons, o.persons)
        && equals(manager_num, o.manager_num)
        && equals(allocate_profit, o.allocate_profit)
        && equals(family_level, o.family_level)
        && equals(isallow, o.isallow);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = isFill != null ? isFill.hashCode() : 0;
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (familyname != null ? familyname.hashCode() : 0);
      result = result * 37 + (familyintro != null ? familyintro.hashCode() : 0);
      result = result * 37 + (familyurl != null ? familyurl.hashCode() : 0);
      result = result * 37 + (coin != null ? coin.hashCode() : 0);
      result = result * 37 + (persons != null ? persons.hashCode() : 0);
      result = result * 37 + (manager_num != null ? manager_num.hashCode() : 0);
      result = result * 37 + (allocate_profit != null ? allocate_profit.hashCode() : 0);
      result = result * 37 + (family_level != null ? family_level.hashCode() : 0);
      result = result * 37 + (isallow != null ? isallow.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_FAMILY_INFO> {

    public Boolean isFill;
    public Integer familyid;
    public String familyname;
    public String familyintro;
    public String familyurl;
    public Integer coin;
    public Integer persons;
    public Integer manager_num;
    public String allocate_profit;
    public Integer family_level;
    public Boolean isallow;

    public Builder() {
    }

    public Builder(PB_FAMILY_INFO message) {
      super(message);
      if (message == null) return;
      this.isFill = message.isFill;
      this.familyid = message.familyid;
      this.familyname = message.familyname;
      this.familyintro = message.familyintro;
      this.familyurl = message.familyurl;
      this.coin = message.coin;
      this.persons = message.persons;
      this.manager_num = message.manager_num;
      this.allocate_profit = message.allocate_profit;
      this.family_level = message.family_level;
      this.isallow = message.isallow;
    }

    /**
     * �Ƿ�Լ�����Ϣ��ֵ��true�м�����Ϣ��false,�޼�����Ϣ
     */
    public Builder isFill(Boolean isFill) {
      this.isFill = isFill;
      return this;
    }

    /**
     * ����id
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * ������
     */
    public Builder familyname(String familyname) {
      this.familyname = familyname;
      return this;
    }

    /**
     * �������
     */
    public Builder familyintro(String familyintro) {
      this.familyintro = familyintro;
      return this;
    }

    /**
     * ����ͷ��
     */
    public Builder familyurl(String familyurl) {
      this.familyurl = familyurl;
      return this;
    }

    /**
     * ������
     */
    public Builder coin(Integer coin) {
      this.coin = coin;
      return this;
    }

    /**
     * ��������
     */
    public Builder persons(Integer persons) {
      this.persons = persons;
      return this;
    }

    /**
     * ����Ա����
     */
    public Builder manager_num(Integer manager_num) {
      this.manager_num = manager_num;
      return this;
    }

    /**
     * ����ֺ�
     */
    public Builder allocate_profit(String allocate_profit) {
      this.allocate_profit = allocate_profit;
      return this;
    }

    /**
     * ����ȼ�
     */
    public Builder family_level(Integer family_level) {
      this.family_level = family_level;
      return this;
    }

    /**
     * �Ƿ�������ռ���������Ϣ
     */
    public Builder isallow(Boolean isallow) {
      this.isallow = isallow;
      return this;
    }

    @Override
    public PB_FAMILY_INFO build() {
      checkRequiredFields();
      return new PB_FAMILY_INFO(this);
    }
  }
}
