// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �������߳��������Ա���
 */
public final class PB_GETOUT_TGUSER_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_GT_TGUSER_Ret DEFAULT_RET = eRS_GT_TGUSER_Ret.eRS_GT_TGU_SUC;
  public static final Long DEFAULT_TGID = 0L;
  public static final Long DEFAULT_TARGET_UID = 0L;

  /**
   * ���
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_GT_TGUSER_Ret ret;

  /**
   * ������ID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * ���߳��ĳ�ԱUID
   */
  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long target_uid;

  public PB_GETOUT_TGUSER_REP(eRS_GT_TGUSER_Ret ret, Long tgid, Long target_uid) {
    this.ret = ret;
    this.tgid = tgid;
    this.target_uid = target_uid;
  }

  private PB_GETOUT_TGUSER_REP(Builder builder) {
    this(builder.ret, builder.tgid, builder.target_uid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_GETOUT_TGUSER_REP)) return false;
    PB_GETOUT_TGUSER_REP o = (PB_GETOUT_TGUSER_REP) other;
    return equals(ret, o.ret)
        && equals(tgid, o.tgid)
        && equals(target_uid, o.target_uid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = ret != null ? ret.hashCode() : 0;
      result = result * 37 + (tgid != null ? tgid.hashCode() : 0);
      result = result * 37 + (target_uid != null ? target_uid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_GETOUT_TGUSER_REP> {

    public eRS_GT_TGUSER_Ret ret;
    public Long tgid;
    public Long target_uid;

    public Builder() {
    }

    public Builder(PB_GETOUT_TGUSER_REP message) {
      super(message);
      if (message == null) return;
      this.ret = message.ret;
      this.tgid = message.tgid;
      this.target_uid = message.target_uid;
    }

    /**
     * ���
     */
    public Builder ret(eRS_GT_TGUSER_Ret ret) {
      this.ret = ret;
      return this;
    }

    /**
     * ������ID
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * ���߳��ĳ�ԱUID
     */
    public Builder target_uid(Long target_uid) {
      this.target_uid = target_uid;
      return this;
    }

    @Override
    public PB_GETOUT_TGUSER_REP build() {
      checkRequiredFields();
      return new PB_GETOUT_TGUSER_REP(this);
    }
  }
}
