// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �������߳��������Ա��Ϣ
 */
public final class PB_GETOUT_TGUSER_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_TGID = 0L;

  /**
   * ������ID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * ������
   */
  @ProtoField(tag = 2, label = REQUIRED)
  public final PB_USER creater;

  /**
   * ���߳��ĳ�Ա
   */
  @ProtoField(tag = 3, label = REQUIRED)
  public final PB_USER target;

  public PB_GETOUT_TGUSER_MSG(Long tgid, PB_USER creater, PB_USER target) {
    this.tgid = tgid;
    this.creater = creater;
    this.target = target;
  }

  private PB_GETOUT_TGUSER_MSG(Builder builder) {
    this(builder.tgid, builder.creater, builder.target);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_GETOUT_TGUSER_MSG)) return false;
    PB_GETOUT_TGUSER_MSG o = (PB_GETOUT_TGUSER_MSG) other;
    return equals(tgid, o.tgid)
        && equals(creater, o.creater)
        && equals(target, o.target);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = tgid != null ? tgid.hashCode() : 0;
      result = result * 37 + (creater != null ? creater.hashCode() : 0);
      result = result * 37 + (target != null ? target.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_GETOUT_TGUSER_MSG> {

    public Long tgid;
    public PB_USER creater;
    public PB_USER target;

    public Builder() {
    }

    public Builder(PB_GETOUT_TGUSER_MSG message) {
      super(message);
      if (message == null) return;
      this.tgid = message.tgid;
      this.creater = message.creater;
      this.target = message.target;
    }

    /**
     * ������ID
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * ������
     */
    public Builder creater(PB_USER creater) {
      this.creater = creater;
      return this;
    }

    /**
     * ���߳��ĳ�Ա
     */
    public Builder target(PB_USER target) {
      this.target = target;
      return this;
    }

    @Override
    public PB_GETOUT_TGUSER_MSG build() {
      checkRequiredFields();
      return new PB_GETOUT_TGUSER_MSG(this);
    }
  }
}
