// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\loginMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_HC_CLIENT_LOGIN extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_ACCOUNT = "";
  public static final String DEFAULT_TOKEN = "";
  public static final Integer DEFAULT_APPID = 0;
  public static final String DEFAULT_APPTOKEN = "";
  public static final Integer DEFAULT_DEVTYPE = 0;
  public static final String DEFAULT_DEVID = "";
  public static final String DEFAULT_SYSVER = "";
  public static final Integer DEFAULT_LOGINTYPE = 0;
  public static final String DEFAULT_TESTWEBRET = "";

  /**
   * UserID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �û��˺�
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String account;

  /**
   * �û�token
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String token;

  /**
   * Ӧ��id
   */
  @ProtoField(tag = 4, type = INT32, label = REQUIRED)
  public final Integer appid;

  /**
   * Ӧ��token
   */
  @ProtoField(tag = 5, type = STRING, label = REQUIRED)
  public final String apptoken;

  /**
   * �豸����0,ios,1, android
   */
  @ProtoField(tag = 6, type = INT32, label = REQUIRED)
  public final Integer devtype;

  /**
   * �豸id
   */
  @ProtoField(tag = 7, type = STRING)
  public final String devid;

  /**
   * �ƶ��˲���ϵͳ�汾
   */
  @ProtoField(tag = 8, type = STRING)
  public final String sysver;

  /**
   * ��½����
   */
  @ProtoField(tag = 9, type = INT32, label = REQUIRED)
  public final Integer logintype;

  /**
   * ���Է��ؽ�� APPID=100ʱ��Ч
   */
  @ProtoField(tag = 10, type = STRING)
  public final String testwebret;

  public PB_HC_CLIENT_LOGIN(Long userid, String account, String token, Integer appid, String apptoken, Integer devtype, String devid, String sysver, Integer logintype, String testwebret) {
    this.userid = userid;
    this.account = account;
    this.token = token;
    this.appid = appid;
    this.apptoken = apptoken;
    this.devtype = devtype;
    this.devid = devid;
    this.sysver = sysver;
    this.logintype = logintype;
    this.testwebret = testwebret;
  }

  private PB_HC_CLIENT_LOGIN(Builder builder) {
    this(builder.userid, builder.account, builder.token, builder.appid, builder.apptoken, builder.devtype, builder.devid, builder.sysver, builder.logintype, builder.testwebret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_HC_CLIENT_LOGIN)) return false;
    PB_HC_CLIENT_LOGIN o = (PB_HC_CLIENT_LOGIN) other;
    return equals(userid, o.userid)
        && equals(account, o.account)
        && equals(token, o.token)
        && equals(appid, o.appid)
        && equals(apptoken, o.apptoken)
        && equals(devtype, o.devtype)
        && equals(devid, o.devid)
        && equals(sysver, o.sysver)
        && equals(logintype, o.logintype)
        && equals(testwebret, o.testwebret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (token != null ? token.hashCode() : 0);
      result = result * 37 + (appid != null ? appid.hashCode() : 0);
      result = result * 37 + (apptoken != null ? apptoken.hashCode() : 0);
      result = result * 37 + (devtype != null ? devtype.hashCode() : 0);
      result = result * 37 + (devid != null ? devid.hashCode() : 0);
      result = result * 37 + (sysver != null ? sysver.hashCode() : 0);
      result = result * 37 + (logintype != null ? logintype.hashCode() : 0);
      result = result * 37 + (testwebret != null ? testwebret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_HC_CLIENT_LOGIN> {

    public Long userid;
    public String account;
    public String token;
    public Integer appid;
    public String apptoken;
    public Integer devtype;
    public String devid;
    public String sysver;
    public Integer logintype;
    public String testwebret;

    public Builder() {
    }

    public Builder(PB_HC_CLIENT_LOGIN message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.account = message.account;
      this.token = message.token;
      this.appid = message.appid;
      this.apptoken = message.apptoken;
      this.devtype = message.devtype;
      this.devid = message.devid;
      this.sysver = message.sysver;
      this.logintype = message.logintype;
      this.testwebret = message.testwebret;
    }

    /**
     * UserID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �û��˺�
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    /**
     * �û�token
     */
    public Builder token(String token) {
      this.token = token;
      return this;
    }

    /**
     * Ӧ��id
     */
    public Builder appid(Integer appid) {
      this.appid = appid;
      return this;
    }

    /**
     * Ӧ��token
     */
    public Builder apptoken(String apptoken) {
      this.apptoken = apptoken;
      return this;
    }

    /**
     * �豸����0,ios,1, android
     */
    public Builder devtype(Integer devtype) {
      this.devtype = devtype;
      return this;
    }

    /**
     * �豸id
     */
    public Builder devid(String devid) {
      this.devid = devid;
      return this;
    }

    /**
     * �ƶ��˲���ϵͳ�汾
     */
    public Builder sysver(String sysver) {
      this.sysver = sysver;
      return this;
    }

    /**
     * ��½����
     */
    public Builder logintype(Integer logintype) {
      this.logintype = logintype;
      return this;
    }

    /**
     * ���Է��ؽ�� APPID=100ʱ��Ч
     */
    public Builder testwebret(String testwebret) {
      this.testwebret = testwebret;
      return this;
    }

    @Override
    public PB_HC_CLIENT_LOGIN build() {
      checkRequiredFields();
      return new PB_HC_CLIENT_LOGIN(this);
    }
  }
}
