// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\loginMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * login server reply client login msg
 */
public final class PB_HC_CLIENT_LOGIN_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final LoginSvr_RetCode DEFAULT_RETCODE = LoginSvr_RetCode.GC_LOGIN_UNKNOW;

  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final LoginSvr_RetCode retcode;

  /**
   * user info,retcode=GC_LOGIN_SUCCʱ����
   */
  @ProtoField(tag = 2)
  public final PB_LOGIN_USERINFO userinfo;

  /**
   * svr info,retcode=GC_LOGIN_SUCCʱ����
   */
  @ProtoField(tag = 3)
  public final PB_ROOMSVR_INFO svrinfo;

  @ProtoField(tag = 4)
  public final PB_FAMILY_INFO familyinfo;

  public PB_HC_CLIENT_LOGIN_REP(LoginSvr_RetCode retcode, PB_LOGIN_USERINFO userinfo, PB_ROOMSVR_INFO svrinfo, PB_FAMILY_INFO familyinfo) {
    this.retcode = retcode;
    this.userinfo = userinfo;
    this.svrinfo = svrinfo;
    this.familyinfo = familyinfo;
  }

  private PB_HC_CLIENT_LOGIN_REP(Builder builder) {
    this(builder.retcode, builder.userinfo, builder.svrinfo, builder.familyinfo);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_HC_CLIENT_LOGIN_REP)) return false;
    PB_HC_CLIENT_LOGIN_REP o = (PB_HC_CLIENT_LOGIN_REP) other;
    return equals(retcode, o.retcode)
        && equals(userinfo, o.userinfo)
        && equals(svrinfo, o.svrinfo)
        && equals(familyinfo, o.familyinfo);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = retcode != null ? retcode.hashCode() : 0;
      result = result * 37 + (userinfo != null ? userinfo.hashCode() : 0);
      result = result * 37 + (svrinfo != null ? svrinfo.hashCode() : 0);
      result = result * 37 + (familyinfo != null ? familyinfo.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_HC_CLIENT_LOGIN_REP> {

    public LoginSvr_RetCode retcode;
    public PB_LOGIN_USERINFO userinfo;
    public PB_ROOMSVR_INFO svrinfo;
    public PB_FAMILY_INFO familyinfo;

    public Builder() {
    }

    public Builder(PB_HC_CLIENT_LOGIN_REP message) {
      super(message);
      if (message == null) return;
      this.retcode = message.retcode;
      this.userinfo = message.userinfo;
      this.svrinfo = message.svrinfo;
      this.familyinfo = message.familyinfo;
    }

    public Builder retcode(LoginSvr_RetCode retcode) {
      this.retcode = retcode;
      return this;
    }

    /**
     * user info,retcode=GC_LOGIN_SUCCʱ����
     */
    public Builder userinfo(PB_LOGIN_USERINFO userinfo) {
      this.userinfo = userinfo;
      return this;
    }

    /**
     * svr info,retcode=GC_LOGIN_SUCCʱ����
     */
    public Builder svrinfo(PB_ROOMSVR_INFO svrinfo) {
      this.svrinfo = svrinfo;
      return this;
    }

    public Builder familyinfo(PB_FAMILY_INFO familyinfo) {
      this.familyinfo = familyinfo;
      return this;
    }

    @Override
    public PB_HC_CLIENT_LOGIN_REP build() {
      checkRequiredFields();
      return new PB_HC_CLIENT_LOGIN_REP(this);
    }
  }
}
