// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_INVITE_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_INVITEID = 0L;
  public static final Integer DEFAULT_ROOMID = 0;
  public static final eRS_Invite_Ret DEFAULT_INVITEREP = eRS_Invite_Ret.eRS_IR_ACCEPT;

  /**
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ������id
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long inviteid;

  /**
   * ����id
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * ����ظ�
   */
  @ProtoField(tag = 4, type = ENUM, label = REQUIRED)
  public final eRS_Invite_Ret inviteRep;

  public PB_INVITE_REP(Long userid, Long inviteid, Integer roomid, eRS_Invite_Ret inviteRep) {
    this.userid = userid;
    this.inviteid = inviteid;
    this.roomid = roomid;
    this.inviteRep = inviteRep;
  }

  private PB_INVITE_REP(Builder builder) {
    this(builder.userid, builder.inviteid, builder.roomid, builder.inviteRep);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_INVITE_REP)) return false;
    PB_INVITE_REP o = (PB_INVITE_REP) other;
    return equals(userid, o.userid)
        && equals(inviteid, o.inviteid)
        && equals(roomid, o.roomid)
        && equals(inviteRep, o.inviteRep);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (inviteid != null ? inviteid.hashCode() : 0);
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      result = result * 37 + (inviteRep != null ? inviteRep.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_INVITE_REP> {

    public Long userid;
    public Long inviteid;
    public Integer roomid;
    public eRS_Invite_Ret inviteRep;

    public Builder() {
    }

    public Builder(PB_INVITE_REP message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.inviteid = message.inviteid;
      this.roomid = message.roomid;
      this.inviteRep = message.inviteRep;
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ������id
     */
    public Builder inviteid(Long inviteid) {
      this.inviteid = inviteid;
      return this;
    }

    /**
     * ����id
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ����ظ�
     */
    public Builder inviteRep(eRS_Invite_Ret inviteRep) {
      this.inviteRep = inviteRep;
      return this;
    }

    @Override
    public PB_INVITE_REP build() {
      checkRequiredFields();
      return new PB_INVITE_REP(this);
    }
  }
}
