// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_IS_BLACK extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_PEERID = 0L;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * �����û�id
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ��Ҫ����ѯ���û�id
   */
  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long peerid;

  public PB_IS_BLACK(Integer roomid, Long userid, Long peerid) {
    this.roomid = roomid;
    this.userid = userid;
    this.peerid = peerid;
  }

  private PB_IS_BLACK(Builder builder) {
    this(builder.roomid, builder.userid, builder.peerid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_IS_BLACK)) return false;
    PB_IS_BLACK o = (PB_IS_BLACK) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(peerid, o.peerid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (peerid != null ? peerid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_IS_BLACK> {

    public Integer roomid;
    public Long userid;
    public Long peerid;

    public Builder() {
    }

    public Builder(PB_IS_BLACK message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.peerid = message.peerid;
    }

    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * �����û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ��Ҫ����ѯ���û�id
     */
    public Builder peerid(Long peerid) {
      this.peerid = peerid;
      return this;
    }

    @Override
    public PB_IS_BLACK build() {
      checkRequiredFields();
      return new PB_IS_BLACK(this);
    }
  }
}
