// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\loginMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * login server reply user info
 */
public final class PB_LOGIN_USERINFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final ePB_COM_SEX DEFAULT_SEX = ePB_COM_SEX.SEX_UNKNOWN;
  public static final String DEFAULT_HEAD_URL = "";
  public static final Long DEFAULT_COIN = 0L;
  public static final Integer DEFAULT_LEVEL = 0;
  public static final Integer DEFAULT_VIP = 0;
  public static final Integer DEFAULT_JOB = 0;
  public static final Long DEFAULT_PRETTYNUM = 0L;

  /**
   * user id  in chat system
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �س�
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String nickname;

  @ProtoField(tag = 3, type = ENUM)
  public final ePB_COM_SEX sex;

  /**
   * ͷ���ַ
   */
  @ProtoField(tag = 4, type = STRING)
  public final String head_url;

  /**
   * ���ֵ
   */
  @ProtoField(tag = 5, type = INT64)
  public final Long coin;

  /**
   * �ȼ�
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer level;

  /**
   * VIP
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer vip;

  /**
   * 0����ͨ��Ա��1������Ա��2�����峤
   */
  @ProtoField(tag = 8, type = INT32)
  public final Integer job;

  /**
   * ����
   */
  @ProtoField(tag = 9, type = INT64)
  public final Long prettynum;

  public PB_LOGIN_USERINFO(Long userid, String nickname, ePB_COM_SEX sex, String head_url, Long coin, Integer level, Integer vip, Integer job, Long prettynum) {
    this.userid = userid;
    this.nickname = nickname;
    this.sex = sex;
    this.head_url = head_url;
    this.coin = coin;
    this.level = level;
    this.vip = vip;
    this.job = job;
    this.prettynum = prettynum;
  }

  private PB_LOGIN_USERINFO(Builder builder) {
    this(builder.userid, builder.nickname, builder.sex, builder.head_url, builder.coin, builder.level, builder.vip, builder.job, builder.prettynum);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_LOGIN_USERINFO)) return false;
    PB_LOGIN_USERINFO o = (PB_LOGIN_USERINFO) other;
    return equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(sex, o.sex)
        && equals(head_url, o.head_url)
        && equals(coin, o.coin)
        && equals(level, o.level)
        && equals(vip, o.vip)
        && equals(job, o.job)
        && equals(prettynum, o.prettynum);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (sex != null ? sex.hashCode() : 0);
      result = result * 37 + (head_url != null ? head_url.hashCode() : 0);
      result = result * 37 + (coin != null ? coin.hashCode() : 0);
      result = result * 37 + (level != null ? level.hashCode() : 0);
      result = result * 37 + (vip != null ? vip.hashCode() : 0);
      result = result * 37 + (job != null ? job.hashCode() : 0);
      result = result * 37 + (prettynum != null ? prettynum.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_LOGIN_USERINFO> {

    public Long userid;
    public String nickname;
    public ePB_COM_SEX sex;
    public String head_url;
    public Long coin;
    public Integer level;
    public Integer vip;
    public Integer job;
    public Long prettynum;

    public Builder() {
    }

    public Builder(PB_LOGIN_USERINFO message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.sex = message.sex;
      this.head_url = message.head_url;
      this.coin = message.coin;
      this.level = message.level;
      this.vip = message.vip;
      this.job = message.job;
      this.prettynum = message.prettynum;
    }

    /**
     * user id  in chat system
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �س�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    public Builder sex(ePB_COM_SEX sex) {
      this.sex = sex;
      return this;
    }

    /**
     * ͷ���ַ
     */
    public Builder head_url(String head_url) {
      this.head_url = head_url;
      return this;
    }

    /**
     * ���ֵ
     */
    public Builder coin(Long coin) {
      this.coin = coin;
      return this;
    }

    /**
     * �ȼ�
     */
    public Builder level(Integer level) {
      this.level = level;
      return this;
    }

    /**
     * VIP
     */
    public Builder vip(Integer vip) {
      this.vip = vip;
      return this;
    }

    /**
     * 0����ͨ��Ա��1������Ա��2�����峤
     */
    public Builder job(Integer job) {
      this.job = job;
      return this;
    }

    /**
     * ����
     */
    public Builder prettynum(Long prettynum) {
      this.prettynum = prettynum;
      return this;
    }

    @Override
    public PB_LOGIN_USERINFO build() {
      checkRequiredFields();
      return new PB_LOGIN_USERINFO(this);
    }
  }
}
