// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_MULTI_OPRATE extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_OPRATEID = 0L;
  public static final Long DEFAULT_ACCEPTID = 0L;
  public static final eRS_Oprate_Type DEFAULT_OPTYPE = eRS_Oprate_Type.RS_OT_SET_MANAGER;
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final Integer DEFAULT_ROOMID = 0;
  public static final String DEFAULT_ACC_ID = "";

  /**
   * ������id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long oprateid;

  /**
   * ��������id
   */
  @ProtoField(tag = 2, type = INT64)
  public final Long acceptid;

  /**
   * ��������
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_Oprate_Type optype;

  /**
   * ����id
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer familyid;

  /**
   * ����id
   */
  @ProtoField(tag = 5, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * ���������˺�id
   */
  @ProtoField(tag = 6, type = STRING, label = REQUIRED)
  public final String acc_id;

  public PB_MULTI_OPRATE(Long oprateid, Long acceptid, eRS_Oprate_Type optype, Integer familyid, Integer roomid, String acc_id) {
    this.oprateid = oprateid;
    this.acceptid = acceptid;
    this.optype = optype;
    this.familyid = familyid;
    this.roomid = roomid;
    this.acc_id = acc_id;
  }

  private PB_MULTI_OPRATE(Builder builder) {
    this(builder.oprateid, builder.acceptid, builder.optype, builder.familyid, builder.roomid, builder.acc_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_MULTI_OPRATE)) return false;
    PB_MULTI_OPRATE o = (PB_MULTI_OPRATE) other;
    return equals(oprateid, o.oprateid)
        && equals(acceptid, o.acceptid)
        && equals(optype, o.optype)
        && equals(familyid, o.familyid)
        && equals(roomid, o.roomid)
        && equals(acc_id, o.acc_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = oprateid != null ? oprateid.hashCode() : 0;
      result = result * 37 + (acceptid != null ? acceptid.hashCode() : 0);
      result = result * 37 + (optype != null ? optype.hashCode() : 0);
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      result = result * 37 + (acc_id != null ? acc_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_MULTI_OPRATE> {

    public Long oprateid;
    public Long acceptid;
    public eRS_Oprate_Type optype;
    public Integer familyid;
    public Integer roomid;
    public String acc_id;

    public Builder() {
    }

    public Builder(PB_MULTI_OPRATE message) {
      super(message);
      if (message == null) return;
      this.oprateid = message.oprateid;
      this.acceptid = message.acceptid;
      this.optype = message.optype;
      this.familyid = message.familyid;
      this.roomid = message.roomid;
      this.acc_id = message.acc_id;
    }

    /**
     * ������id
     */
    public Builder oprateid(Long oprateid) {
      this.oprateid = oprateid;
      return this;
    }

    /**
     * ��������id
     */
    public Builder acceptid(Long acceptid) {
      this.acceptid = acceptid;
      return this;
    }

    /**
     * ��������
     */
    public Builder optype(eRS_Oprate_Type optype) {
      this.optype = optype;
      return this;
    }

    /**
     * ����id
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * ����id
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ���������˺�id
     */
    public Builder acc_id(String acc_id) {
      this.acc_id = acc_id;
      return this;
    }

    @Override
    public PB_MULTI_OPRATE build() {
      checkRequiredFields();
      return new PB_MULTI_OPRATE(this);
    }
  }
}
