// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_MULTI_OPRATE_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_Oprate_Type DEFAULT_OPTYPE = eRS_Oprate_Type.RS_OT_SET_MANAGER;
  public static final eRS_Oprate_Relation_Ret DEFAULT_OPTRET = eRS_Oprate_Relation_Ret.eRS_OR_SUC;
  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_TARGETID = 0L;

  /**
   * ��������
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_Oprate_Type optype;

  /**
   * ��ϵ����
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final eRS_Oprate_Relation_Ret optret;

  /**
   * �û�id
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long userid;

  /**
   * Ŀ���û�userid
   */
  @ProtoField(tag = 4, type = INT64)
  public final Long targetid;

  public PB_MULTI_OPRATE_REP(eRS_Oprate_Type optype, eRS_Oprate_Relation_Ret optret, Long userid, Long targetid) {
    this.optype = optype;
    this.optret = optret;
    this.userid = userid;
    this.targetid = targetid;
  }

  private PB_MULTI_OPRATE_REP(Builder builder) {
    this(builder.optype, builder.optret, builder.userid, builder.targetid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_MULTI_OPRATE_REP)) return false;
    PB_MULTI_OPRATE_REP o = (PB_MULTI_OPRATE_REP) other;
    return equals(optype, o.optype)
        && equals(optret, o.optret)
        && equals(userid, o.userid)
        && equals(targetid, o.targetid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = optype != null ? optype.hashCode() : 0;
      result = result * 37 + (optret != null ? optret.hashCode() : 0);
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (targetid != null ? targetid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_MULTI_OPRATE_REP> {

    public eRS_Oprate_Type optype;
    public eRS_Oprate_Relation_Ret optret;
    public Long userid;
    public Long targetid;

    public Builder() {
    }

    public Builder(PB_MULTI_OPRATE_REP message) {
      super(message);
      if (message == null) return;
      this.optype = message.optype;
      this.optret = message.optret;
      this.userid = message.userid;
      this.targetid = message.targetid;
    }

    /**
     * ��������
     */
    public Builder optype(eRS_Oprate_Type optype) {
      this.optype = optype;
      return this;
    }

    /**
     * ��ϵ����
     */
    public Builder optret(eRS_Oprate_Relation_Ret optret) {
      this.optret = optret;
      return this;
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * Ŀ���û�userid
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    @Override
    public PB_MULTI_OPRATE_REP build() {
      checkRequiredFields();
      return new PB_MULTI_OPRATE_REP(this);
    }
  }
}
