// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �µ�֪ͨ��Ϣ
 */
public final class PB_NEW_NOTICE_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_NOTICE_ID = 0L;
  public static final eNOTICE_MSG_TYPE DEFAULT_NOTICETYPE = eNOTICE_MSG_TYPE.NOTICE_MSG_TYPE_FRD;
  public static final String DEFAULT_TITLE = "";
  public static final String DEFAULT_CONTENT = "";
  public static final String DEFAULT_ICONURL = "";
  public static final Integer DEFAULT_TIME = 0;
  public static final Integer DEFAULT_UNREAD_NUM = 0;

  /**
   * ֪ͨID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long notice_id;

  /**
   * ֪ͨ����
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final eNOTICE_MSG_TYPE noticeType;

  /**
   * ����
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String title;

  /**
   * ����
   */
  @ProtoField(tag = 4, type = STRING, label = REQUIRED)
  public final String content;

  /**
   * ͼ��
   */
  @ProtoField(tag = 5, type = STRING)
  public final String iconurl;

  /**
   * ����ʱ��
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer time;

  /**
   * ��Ϣδ����
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer unread_num;

  public PB_NEW_NOTICE_MSG(Long notice_id, eNOTICE_MSG_TYPE noticeType, String title, String content, String iconurl, Integer time, Integer unread_num) {
    this.notice_id = notice_id;
    this.noticeType = noticeType;
    this.title = title;
    this.content = content;
    this.iconurl = iconurl;
    this.time = time;
    this.unread_num = unread_num;
  }

  private PB_NEW_NOTICE_MSG(Builder builder) {
    this(builder.notice_id, builder.noticeType, builder.title, builder.content, builder.iconurl, builder.time, builder.unread_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_NEW_NOTICE_MSG)) return false;
    PB_NEW_NOTICE_MSG o = (PB_NEW_NOTICE_MSG) other;
    return equals(notice_id, o.notice_id)
        && equals(noticeType, o.noticeType)
        && equals(title, o.title)
        && equals(content, o.content)
        && equals(iconurl, o.iconurl)
        && equals(time, o.time)
        && equals(unread_num, o.unread_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = notice_id != null ? notice_id.hashCode() : 0;
      result = result * 37 + (noticeType != null ? noticeType.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (iconurl != null ? iconurl.hashCode() : 0);
      result = result * 37 + (time != null ? time.hashCode() : 0);
      result = result * 37 + (unread_num != null ? unread_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_NEW_NOTICE_MSG> {

    public Long notice_id;
    public eNOTICE_MSG_TYPE noticeType;
    public String title;
    public String content;
    public String iconurl;
    public Integer time;
    public Integer unread_num;

    public Builder() {
    }

    public Builder(PB_NEW_NOTICE_MSG message) {
      super(message);
      if (message == null) return;
      this.notice_id = message.notice_id;
      this.noticeType = message.noticeType;
      this.title = message.title;
      this.content = message.content;
      this.iconurl = message.iconurl;
      this.time = message.time;
      this.unread_num = message.unread_num;
    }

    /**
     * ֪ͨID
     */
    public Builder notice_id(Long notice_id) {
      this.notice_id = notice_id;
      return this;
    }

    /**
     * ֪ͨ����
     */
    public Builder noticeType(eNOTICE_MSG_TYPE noticeType) {
      this.noticeType = noticeType;
      return this;
    }

    /**
     * ����
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    /**
     * ����
     */
    public Builder content(String content) {
      this.content = content;
      return this;
    }

    /**
     * ͼ��
     */
    public Builder iconurl(String iconurl) {
      this.iconurl = iconurl;
      return this;
    }

    /**
     * ����ʱ��
     */
    public Builder time(Integer time) {
      this.time = time;
      return this;
    }

    /**
     * ��Ϣδ����
     */
    public Builder unread_num(Integer unread_num) {
      this.unread_num = unread_num;
      return this;
    }

    @Override
    public PB_NEW_NOTICE_MSG build() {
      checkRequiredFields();
      return new PB_NEW_NOTICE_MSG(this);
    }
  }
}
