// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ֪ͨ��Ϣ
 */
public final class PB_NOTICE_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_NOTICE_ID = 0L;
  public static final eNOTICE_CTRL_STYLE DEFAULT_CTRLSTYLE = eNOTICE_CTRL_STYLE.NOTICE_CTRL_UNKNOWN;
  public static final String DEFAULT_TITLE = "";
  public static final String DEFAULT_CONTENT = "";
  public static final String DEFAULT_SUBTXT = "";
  public static final String DEFAULT_ICONURL = "";
  public static final Integer DEFAULT_TIME = 0;
  public static final Long DEFAULT_TARGETID = 0L;
  public static final String DEFAULT_ACCOUNT = "";

  /**
   * ֪ͨID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long notice_id;

  /**
   * ֪ͨ��ʽ
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final eNOTICE_CTRL_STYLE ctrlStyle;

  /**
   * ����
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String title;

  /**
   * ����
   */
  @ProtoField(tag = 4, type = STRING, label = REQUIRED)
  public final String content;

  /**
   * ������
   */
  @ProtoField(tag = 5, type = STRING)
  public final String subtxt;

  /**
   * ͼ��
   */
  @ProtoField(tag = 6, type = STRING)
  public final String iconurl;

  /**
   * ����ʱ��
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer time;

  /**
   * Ŀ��ID ������ID��������Id,����Id��
   */
  @ProtoField(tag = 8, type = INT64)
  public final Long targetid;

  /**
   * �û��˺�
   */
  @ProtoField(tag = 9, type = STRING)
  public final String account;

  public PB_NOTICE_MSG(Long notice_id, eNOTICE_CTRL_STYLE ctrlStyle, String title, String content, String subtxt, String iconurl, Integer time, Long targetid, String account) {
    this.notice_id = notice_id;
    this.ctrlStyle = ctrlStyle;
    this.title = title;
    this.content = content;
    this.subtxt = subtxt;
    this.iconurl = iconurl;
    this.time = time;
    this.targetid = targetid;
    this.account = account;
  }

  private PB_NOTICE_MSG(Builder builder) {
    this(builder.notice_id, builder.ctrlStyle, builder.title, builder.content, builder.subtxt, builder.iconurl, builder.time, builder.targetid, builder.account);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_NOTICE_MSG)) return false;
    PB_NOTICE_MSG o = (PB_NOTICE_MSG) other;
    return equals(notice_id, o.notice_id)
        && equals(ctrlStyle, o.ctrlStyle)
        && equals(title, o.title)
        && equals(content, o.content)
        && equals(subtxt, o.subtxt)
        && equals(iconurl, o.iconurl)
        && equals(time, o.time)
        && equals(targetid, o.targetid)
        && equals(account, o.account);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = notice_id != null ? notice_id.hashCode() : 0;
      result = result * 37 + (ctrlStyle != null ? ctrlStyle.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (subtxt != null ? subtxt.hashCode() : 0);
      result = result * 37 + (iconurl != null ? iconurl.hashCode() : 0);
      result = result * 37 + (time != null ? time.hashCode() : 0);
      result = result * 37 + (targetid != null ? targetid.hashCode() : 0);
      result = result * 37 + (account != null ? account.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_NOTICE_MSG> {

    public Long notice_id;
    public eNOTICE_CTRL_STYLE ctrlStyle;
    public String title;
    public String content;
    public String subtxt;
    public String iconurl;
    public Integer time;
    public Long targetid;
    public String account;

    public Builder() {
    }

    public Builder(PB_NOTICE_MSG message) {
      super(message);
      if (message == null) return;
      this.notice_id = message.notice_id;
      this.ctrlStyle = message.ctrlStyle;
      this.title = message.title;
      this.content = message.content;
      this.subtxt = message.subtxt;
      this.iconurl = message.iconurl;
      this.time = message.time;
      this.targetid = message.targetid;
      this.account = message.account;
    }

    /**
     * ֪ͨID
     */
    public Builder notice_id(Long notice_id) {
      this.notice_id = notice_id;
      return this;
    }

    /**
     * ֪ͨ��ʽ
     */
    public Builder ctrlStyle(eNOTICE_CTRL_STYLE ctrlStyle) {
      this.ctrlStyle = ctrlStyle;
      return this;
    }

    /**
     * ����
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    /**
     * ����
     */
    public Builder content(String content) {
      this.content = content;
      return this;
    }

    /**
     * ������
     */
    public Builder subtxt(String subtxt) {
      this.subtxt = subtxt;
      return this;
    }

    /**
     * ͼ��
     */
    public Builder iconurl(String iconurl) {
      this.iconurl = iconurl;
      return this;
    }

    /**
     * ����ʱ��
     */
    public Builder time(Integer time) {
      this.time = time;
      return this;
    }

    /**
     * Ŀ��ID ������ID��������Id,����Id��
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    /**
     * �û��˺�
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    @Override
    public PB_NOTICE_MSG build() {
      checkRequiredFields();
      return new PB_NOTICE_MSG(this);
    }
  }
}
