// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_OPRATE_DATA_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_MANAGERID = 0L;
  public static final String DEFAULT_HEADURL = "";
  public static final String DEFAULT_NICKNAME = "";
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final String DEFAULT_FAMILYICON = "";
  public static final String DEFAULT_FAMILYNAME = "";

  /**
   * ����Աid
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long managerid;

  /**
   * ����Աͷ��
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String headurl;

  /**
   * ����Ա�س�
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String nickname;

  /**
   * ����id
   */
  @ProtoField(tag = 4, type = INT32, label = REQUIRED)
  public final Integer familyid;

  /**
   * ����ͷ��
   */
  @ProtoField(tag = 5, type = STRING, label = REQUIRED)
  public final String familyicon;

  /**
   * ��������
   */
  @ProtoField(tag = 6, type = STRING, label = REQUIRED)
  public final String familyname;

  public PB_OPRATE_DATA_REP(Long managerid, String headurl, String nickname, Integer familyid, String familyicon, String familyname) {
    this.managerid = managerid;
    this.headurl = headurl;
    this.nickname = nickname;
    this.familyid = familyid;
    this.familyicon = familyicon;
    this.familyname = familyname;
  }

  private PB_OPRATE_DATA_REP(Builder builder) {
    this(builder.managerid, builder.headurl, builder.nickname, builder.familyid, builder.familyicon, builder.familyname);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_OPRATE_DATA_REP)) return false;
    PB_OPRATE_DATA_REP o = (PB_OPRATE_DATA_REP) other;
    return equals(managerid, o.managerid)
        && equals(headurl, o.headurl)
        && equals(nickname, o.nickname)
        && equals(familyid, o.familyid)
        && equals(familyicon, o.familyicon)
        && equals(familyname, o.familyname);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = managerid != null ? managerid.hashCode() : 0;
      result = result * 37 + (headurl != null ? headurl.hashCode() : 0);
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (familyicon != null ? familyicon.hashCode() : 0);
      result = result * 37 + (familyname != null ? familyname.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_OPRATE_DATA_REP> {

    public Long managerid;
    public String headurl;
    public String nickname;
    public Integer familyid;
    public String familyicon;
    public String familyname;

    public Builder() {
    }

    public Builder(PB_OPRATE_DATA_REP message) {
      super(message);
      if (message == null) return;
      this.managerid = message.managerid;
      this.headurl = message.headurl;
      this.nickname = message.nickname;
      this.familyid = message.familyid;
      this.familyicon = message.familyicon;
      this.familyname = message.familyname;
    }

    /**
     * ����Աid
     */
    public Builder managerid(Long managerid) {
      this.managerid = managerid;
      return this;
    }

    /**
     * ����Աͷ��
     */
    public Builder headurl(String headurl) {
      this.headurl = headurl;
      return this;
    }

    /**
     * ����Ա�س�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * ����id
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * ����ͷ��
     */
    public Builder familyicon(String familyicon) {
      this.familyicon = familyicon;
      return this;
    }

    /**
     * ��������
     */
    public Builder familyname(String familyname) {
      this.familyname = familyname;
      return this;
    }

    @Override
    public PB_OPRATE_DATA_REP build() {
      checkRequiredFields();
      return new PB_OPRATE_DATA_REP(this);
    }
  }
}
