// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������Ϣ�ظ�
 */
public final class PB_OPRATE_MSG_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_COMMON_Ret DEFAULT_RET = eRS_COMMON_Ret.eRS_COMMON_SUC;

  @ProtoField(tag = 1, label = REQUIRED)
  public final PB_OPRATE_MSG optmsg;

  /**
   * �������ظ�ֵ
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_Ret ret;

  public PB_OPRATE_MSG_REP(PB_OPRATE_MSG optmsg, eRS_COMMON_Ret ret) {
    this.optmsg = optmsg;
    this.ret = ret;
  }

  private PB_OPRATE_MSG_REP(Builder builder) {
    this(builder.optmsg, builder.ret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_OPRATE_MSG_REP)) return false;
    PB_OPRATE_MSG_REP o = (PB_OPRATE_MSG_REP) other;
    return equals(optmsg, o.optmsg)
        && equals(ret, o.ret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = optmsg != null ? optmsg.hashCode() : 0;
      result = result * 37 + (ret != null ? ret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_OPRATE_MSG_REP> {

    public PB_OPRATE_MSG optmsg;
    public eRS_COMMON_Ret ret;

    public Builder() {
    }

    public Builder(PB_OPRATE_MSG_REP message) {
      super(message);
      if (message == null) return;
      this.optmsg = message.optmsg;
      this.ret = message.ret;
    }

    public Builder optmsg(PB_OPRATE_MSG optmsg) {
      this.optmsg = optmsg;
      return this;
    }

    /**
     * �������ظ�ֵ
     */
    public Builder ret(eRS_COMMON_Ret ret) {
      this.ret = ret;
      return this;
    }

    @Override
    public PB_OPRATE_MSG_REP build() {
      checkRequiredFields();
      return new PB_OPRATE_MSG_REP(this);
    }
  }
}
