// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ��Ϣ����
 */
public final class PB_OPRATE_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;
  public static final Long DEFAULT_MSGID = 0L;
  public static final eRS_MSG_OPRATION DEFAULT_MSGWAY = eRS_MSG_OPRATION.eRS_MSG_HIDE;
  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_TARGETID = 0L;

  /**
   * Ҫɾ������Ϣ����
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  /**
   * Ҫɾ������Ϣ��
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long msgid;

  /**
   * ��Ϣ������ʽ
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_MSG_OPRATION msgway;

  /**
   * ������
   */
  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ������ϢĿ��
   */
  @ProtoField(tag = 5, type = INT64, label = REQUIRED)
  public final Long targetid;

  public PB_OPRATE_MSG(eRS_COMMON_ZONE zone, Long msgid, eRS_MSG_OPRATION msgway, Long userid, Long targetid) {
    this.zone = zone;
    this.msgid = msgid;
    this.msgway = msgway;
    this.userid = userid;
    this.targetid = targetid;
  }

  private PB_OPRATE_MSG(Builder builder) {
    this(builder.zone, builder.msgid, builder.msgway, builder.userid, builder.targetid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_OPRATE_MSG)) return false;
    PB_OPRATE_MSG o = (PB_OPRATE_MSG) other;
    return equals(zone, o.zone)
        && equals(msgid, o.msgid)
        && equals(msgway, o.msgway)
        && equals(userid, o.userid)
        && equals(targetid, o.targetid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = zone != null ? zone.hashCode() : 0;
      result = result * 37 + (msgid != null ? msgid.hashCode() : 0);
      result = result * 37 + (msgway != null ? msgway.hashCode() : 0);
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (targetid != null ? targetid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_OPRATE_MSG> {

    public eRS_COMMON_ZONE zone;
    public Long msgid;
    public eRS_MSG_OPRATION msgway;
    public Long userid;
    public Long targetid;

    public Builder() {
    }

    public Builder(PB_OPRATE_MSG message) {
      super(message);
      if (message == null) return;
      this.zone = message.zone;
      this.msgid = message.msgid;
      this.msgway = message.msgway;
      this.userid = message.userid;
      this.targetid = message.targetid;
    }

    /**
     * Ҫɾ������Ϣ����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    /**
     * Ҫɾ������Ϣ��
     */
    public Builder msgid(Long msgid) {
      this.msgid = msgid;
      return this;
    }

    /**
     * ��Ϣ������ʽ
     */
    public Builder msgway(eRS_MSG_OPRATION msgway) {
      this.msgway = msgway;
      return this;
    }

    /**
     * ������
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ������ϢĿ��
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    @Override
    public PB_OPRATE_MSG build() {
      checkRequiredFields();
      return new PB_OPRATE_MSG(this);
    }
  }
}
