// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������������Ϣ
 */
public final class PB_OFF_BLACK_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final List<Long> DEFAULT_PEERS = Collections.emptyList();
  public static final eRS_BLACK_ZONE DEFAULT_ZONE = eRS_BLACK_ZONE.eRS_BLACK_SET;

  /**
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64)
  public final Long userid;

  /**
   * �����������б�
   */
  @ProtoField(tag = 2, type = INT64, label = REPEATED)
  public final List<Long> peers;

  /**
   * ����������
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_BLACK_ZONE zone;

  public PB_OFF_BLACK_MSG(Long userid, List<Long> peers, eRS_BLACK_ZONE zone) {
    this.userid = userid;
    this.peers = immutableCopyOf(peers);
    this.zone = zone;
  }

  private PB_OFF_BLACK_MSG(Builder builder) {
    this(builder.userid, builder.peers, builder.zone);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_OFF_BLACK_MSG)) return false;
    PB_OFF_BLACK_MSG o = (PB_OFF_BLACK_MSG) other;
    return equals(userid, o.userid)
        && equals(peers, o.peers)
        && equals(zone, o.zone);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (peers != null ? peers.hashCode() : 1);
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_OFF_BLACK_MSG> {

    public Long userid;
    public List<Long> peers;
    public eRS_BLACK_ZONE zone;

    public Builder() {
    }

    public Builder(PB_OFF_BLACK_MSG message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.peers = copyOf(message.peers);
      this.zone = message.zone;
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �����������б�
     */
    public Builder peers(List<Long> peers) {
      this.peers = checkForNulls(peers);
      return this;
    }

    /**
     * ����������
     */
    public Builder zone(eRS_BLACK_ZONE zone) {
      this.zone = zone;
      return this;
    }

    @Override
    public PB_OFF_BLACK_MSG build() {
      checkRequiredFields();
      return new PB_OFF_BLACK_MSG(this);
    }
  }
}
