// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �������ûظ�
 */
public final class PB_PUSH_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_TARGETID = 0L;
  public static final ePB_CHAT_ZONE DEFAULT_CHATZONE = ePB_CHAT_ZONE.CM_ZONE_FAM_NORMAL;
  public static final eRS_PUSH_SET_Ret DEFAULT_RET = eRS_PUSH_SET_Ret.eRS_PUSH_SUC;

  /**
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long targetid;

  /**
   * ��������
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final ePB_CHAT_ZONE chatzone;

  /**
   * �������ͽ��
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_PUSH_SET_Ret ret;

  public PB_PUSH_REP(Long targetid, ePB_CHAT_ZONE chatzone, eRS_PUSH_SET_Ret ret) {
    this.targetid = targetid;
    this.chatzone = chatzone;
    this.ret = ret;
  }

  private PB_PUSH_REP(Builder builder) {
    this(builder.targetid, builder.chatzone, builder.ret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_PUSH_REP)) return false;
    PB_PUSH_REP o = (PB_PUSH_REP) other;
    return equals(targetid, o.targetid)
        && equals(chatzone, o.chatzone)
        && equals(ret, o.ret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = targetid != null ? targetid.hashCode() : 0;
      result = result * 37 + (chatzone != null ? chatzone.hashCode() : 0);
      result = result * 37 + (ret != null ? ret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_PUSH_REP> {

    public Long targetid;
    public ePB_CHAT_ZONE chatzone;
    public eRS_PUSH_SET_Ret ret;

    public Builder() {
    }

    public Builder(PB_PUSH_REP message) {
      super(message);
      if (message == null) return;
      this.targetid = message.targetid;
      this.chatzone = message.chatzone;
      this.ret = message.ret;
    }

    /**
     * �û�id
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    /**
     * ��������
     */
    public Builder chatzone(ePB_CHAT_ZONE chatzone) {
      this.chatzone = chatzone;
      return this;
    }

    /**
     * �������ͽ��
     */
    public Builder ret(eRS_PUSH_SET_Ret ret) {
      this.ret = ret;
      return this;
    }

    @Override
    public PB_PUSH_REP build() {
      checkRequiredFields();
      return new PB_PUSH_REP(this);
    }
  }
}
