// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������Ϣ����
 */
public final class PB_PUSH_MSG_SETS extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<PB_PUSH_NOTICE_MSG> DEFAULT_MSGSETS = Collections.emptyList();
  public static final String DEFAULT_PUSHTOKEN = "";
  public static final String DEFAULT_PUSHTIME = "";

  /**
   * ������Ϣ����
   */
  @ProtoField(tag = 1, label = REPEATED, messageType = PB_PUSH_NOTICE_MSG.class)
  public final List<PB_PUSH_NOTICE_MSG> msgsets;

  /**
   * ����ƾ֤
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String pushtoken;

  /**
   * ����ʱ��
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String pushtime;

  public PB_PUSH_MSG_SETS(List<PB_PUSH_NOTICE_MSG> msgsets, String pushtoken, String pushtime) {
    this.msgsets = immutableCopyOf(msgsets);
    this.pushtoken = pushtoken;
    this.pushtime = pushtime;
  }

  private PB_PUSH_MSG_SETS(Builder builder) {
    this(builder.msgsets, builder.pushtoken, builder.pushtime);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_PUSH_MSG_SETS)) return false;
    PB_PUSH_MSG_SETS o = (PB_PUSH_MSG_SETS) other;
    return equals(msgsets, o.msgsets)
        && equals(pushtoken, o.pushtoken)
        && equals(pushtime, o.pushtime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = msgsets != null ? msgsets.hashCode() : 1;
      result = result * 37 + (pushtoken != null ? pushtoken.hashCode() : 0);
      result = result * 37 + (pushtime != null ? pushtime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_PUSH_MSG_SETS> {

    public List<PB_PUSH_NOTICE_MSG> msgsets;
    public String pushtoken;
    public String pushtime;

    public Builder() {
    }

    public Builder(PB_PUSH_MSG_SETS message) {
      super(message);
      if (message == null) return;
      this.msgsets = copyOf(message.msgsets);
      this.pushtoken = message.pushtoken;
      this.pushtime = message.pushtime;
    }

    /**
     * ������Ϣ����
     */
    public Builder msgsets(List<PB_PUSH_NOTICE_MSG> msgsets) {
      this.msgsets = checkForNulls(msgsets);
      return this;
    }

    /**
     * ����ƾ֤
     */
    public Builder pushtoken(String pushtoken) {
      this.pushtoken = pushtoken;
      return this;
    }

    /**
     * ����ʱ��
     */
    public Builder pushtime(String pushtime) {
      this.pushtime = pushtime;
      return this;
    }

    @Override
    public PB_PUSH_MSG_SETS build() {
      checkRequiredFields();
      return new PB_PUSH_MSG_SETS(this);
    }
  }
}
