// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������Ϣ
 */
public final class PB_PERSONAL_MSG_INFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_UNREAD_CNT = 0L;
  public static final eRS_COMMON_ZONE DEFAULT_MSGZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;

  /**
   * ������
   */
  @ProtoField(tag = 1, label = REQUIRED)
  public final PB_USER user;

  /**
   * ���һ����Ϣ
   */
  @ProtoField(tag = 2)
  public final PB_RS_MSG_INFO last_msg;

  /**
   * δ����Ϣ��
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long unread_cnt;

  /**
   * ������Ϣ����
   */
  @ProtoField(tag = 4, type = ENUM)
  public final eRS_COMMON_ZONE msgzone;

  public PB_PERSONAL_MSG_INFO(PB_USER user, PB_RS_MSG_INFO last_msg, Long unread_cnt, eRS_COMMON_ZONE msgzone) {
    this.user = user;
    this.last_msg = last_msg;
    this.unread_cnt = unread_cnt;
    this.msgzone = msgzone;
  }

  private PB_PERSONAL_MSG_INFO(Builder builder) {
    this(builder.user, builder.last_msg, builder.unread_cnt, builder.msgzone);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_PERSONAL_MSG_INFO)) return false;
    PB_PERSONAL_MSG_INFO o = (PB_PERSONAL_MSG_INFO) other;
    return equals(user, o.user)
        && equals(last_msg, o.last_msg)
        && equals(unread_cnt, o.unread_cnt)
        && equals(msgzone, o.msgzone);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = user != null ? user.hashCode() : 0;
      result = result * 37 + (last_msg != null ? last_msg.hashCode() : 0);
      result = result * 37 + (unread_cnt != null ? unread_cnt.hashCode() : 0);
      result = result * 37 + (msgzone != null ? msgzone.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_PERSONAL_MSG_INFO> {

    public PB_USER user;
    public PB_RS_MSG_INFO last_msg;
    public Long unread_cnt;
    public eRS_COMMON_ZONE msgzone;

    public Builder() {
    }

    public Builder(PB_PERSONAL_MSG_INFO message) {
      super(message);
      if (message == null) return;
      this.user = message.user;
      this.last_msg = message.last_msg;
      this.unread_cnt = message.unread_cnt;
      this.msgzone = message.msgzone;
    }

    /**
     * ������
     */
    public Builder user(PB_USER user) {
      this.user = user;
      return this;
    }

    /**
     * ���һ����Ϣ
     */
    public Builder last_msg(PB_RS_MSG_INFO last_msg) {
      this.last_msg = last_msg;
      return this;
    }

    /**
     * δ����Ϣ��
     */
    public Builder unread_cnt(Long unread_cnt) {
      this.unread_cnt = unread_cnt;
      return this;
    }

    /**
     * ������Ϣ����
     */
    public Builder msgzone(eRS_COMMON_ZONE msgzone) {
      this.msgzone = msgzone;
      return this;
    }

    @Override
    public PB_PERSONAL_MSG_INFO build() {
      checkRequiredFields();
      return new PB_PERSONAL_MSG_INFO(this);
    }
  }
}
