// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * server reply client enter room msg
 */
public final class PB_RS_ENTERROOM_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final RS_Enter_RetCode DEFAULT_LOGINRET = RS_Enter_RetCode.RS_LOGIN_UNKNOW;

  /**
   * pg uid
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ret code
   */
  @ProtoField(tag = 2, type = ENUM, label = REQUIRED)
  public final RS_Enter_RetCode loginret;

  @ProtoField(tag = 3)
  public final PB_RS_USERINFO myuserinfo;

  @ProtoField(tag = 4)
  public final PB_RS_ROOM_INFO roominfo;

  public PB_RS_ENTERROOM_REP(Long userid, RS_Enter_RetCode loginret, PB_RS_USERINFO myuserinfo, PB_RS_ROOM_INFO roominfo) {
    this.userid = userid;
    this.loginret = loginret;
    this.myuserinfo = myuserinfo;
    this.roominfo = roominfo;
  }

  private PB_RS_ENTERROOM_REP(Builder builder) {
    this(builder.userid, builder.loginret, builder.myuserinfo, builder.roominfo);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_ENTERROOM_REP)) return false;
    PB_RS_ENTERROOM_REP o = (PB_RS_ENTERROOM_REP) other;
    return equals(userid, o.userid)
        && equals(loginret, o.loginret)
        && equals(myuserinfo, o.myuserinfo)
        && equals(roominfo, o.roominfo);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (loginret != null ? loginret.hashCode() : 0);
      result = result * 37 + (myuserinfo != null ? myuserinfo.hashCode() : 0);
      result = result * 37 + (roominfo != null ? roominfo.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_ENTERROOM_REP> {

    public Long userid;
    public RS_Enter_RetCode loginret;
    public PB_RS_USERINFO myuserinfo;
    public PB_RS_ROOM_INFO roominfo;

    public Builder() {
    }

    public Builder(PB_RS_ENTERROOM_REP message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.loginret = message.loginret;
      this.myuserinfo = message.myuserinfo;
      this.roominfo = message.roominfo;
    }

    /**
     * pg uid
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ret code
     */
    public Builder loginret(RS_Enter_RetCode loginret) {
      this.loginret = loginret;
      return this;
    }

    public Builder myuserinfo(PB_RS_USERINFO myuserinfo) {
      this.myuserinfo = myuserinfo;
      return this;
    }

    public Builder roominfo(PB_RS_ROOM_INFO roominfo) {
      this.roominfo = roominfo;
      return this;
    }

    @Override
    public PB_RS_ENTERROOM_REP build() {
      checkRequiredFields();
      return new PB_RS_ENTERROOM_REP(this);
    }
  }
}
