// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �����������˳�������Ϣ
 */
public final class PB_RS_QUIT_FAMILY extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_QuitFamily_Ret DEFAULT_RET = eRS_QuitFamily_Ret.RS_QF_SUCC;
  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final Long DEFAULT_FAMILYID = 0L;
  public static final Integer DEFAULT_NEW_ROOMID = 0;

  /**
   * ���
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_QuitFamily_Ret ret;

  /**
   * UID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �ɹ��˳���ʱ����д�����˳��ߵ���Ϣ
   * �ǳ�
   */
  @ProtoField(tag = 3, type = STRING)
  public final String nickname;

  /**
   * �˳��ļ���ID
   */
  @ProtoField(tag = 4, type = INT64)
  public final Long familyid;

  /**
   * �˳����µķ���ID
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer new_roomid;

  public PB_RS_QUIT_FAMILY(eRS_QuitFamily_Ret ret, Long userid, String nickname, Long familyid, Integer new_roomid) {
    this.ret = ret;
    this.userid = userid;
    this.nickname = nickname;
    this.familyid = familyid;
    this.new_roomid = new_roomid;
  }

  private PB_RS_QUIT_FAMILY(Builder builder) {
    this(builder.ret, builder.userid, builder.nickname, builder.familyid, builder.new_roomid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_QUIT_FAMILY)) return false;
    PB_RS_QUIT_FAMILY o = (PB_RS_QUIT_FAMILY) other;
    return equals(ret, o.ret)
        && equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(familyid, o.familyid)
        && equals(new_roomid, o.new_roomid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = ret != null ? ret.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (new_roomid != null ? new_roomid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_QUIT_FAMILY> {

    public eRS_QuitFamily_Ret ret;
    public Long userid;
    public String nickname;
    public Long familyid;
    public Integer new_roomid;

    public Builder() {
    }

    public Builder(PB_RS_QUIT_FAMILY message) {
      super(message);
      if (message == null) return;
      this.ret = message.ret;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.familyid = message.familyid;
      this.new_roomid = message.new_roomid;
    }

    /**
     * ���
     */
    public Builder ret(eRS_QuitFamily_Ret ret) {
      this.ret = ret;
      return this;
    }

    /**
     * UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �ɹ��˳���ʱ����д�����˳��ߵ���Ϣ
     * �ǳ�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * �˳��ļ���ID
     */
    public Builder familyid(Long familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * �˳����µķ���ID
     */
    public Builder new_roomid(Integer new_roomid) {
      this.new_roomid = new_roomid;
      return this;
    }

    @Override
    public PB_RS_QUIT_FAMILY build() {
      checkRequiredFields();
      return new PB_RS_QUIT_FAMILY(this);
    }
  }
}
