// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ��������������������ظ�
 */
public final class PB_RS_ADDFAM_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_MGR_USERID = 0L;
  public static final String DEFAULT_MGR_NICKNAME = "";
  public static final Long DEFAULT_REQUST_USERID = 0L;
  public static final ePB_ADDFAM_REPCMD DEFAULT_CTRL = ePB_ADDFAM_REPCMD.AFM_ACCEPT;

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * ����ߵ��û�ID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long mgr_userid;

  /**
   * ����ߵ��ǳ�
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String mgr_nickname;

  /**
   * ��������UID
   */
  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long requst_userid;

  /**
   * �ظ�����ֵ
   */
  @ProtoField(tag = 5, type = ENUM, label = REQUIRED)
  public final ePB_ADDFAM_REPCMD ctrl;

  /**
   * ������Ϣ(ͬ���ʱ����������)
   */
  @ProtoField(tag = 6)
  public final PB_FAMILY info;

  public PB_RS_ADDFAM_REP(Integer roomid, Long mgr_userid, String mgr_nickname, Long requst_userid, ePB_ADDFAM_REPCMD ctrl, PB_FAMILY info) {
    this.roomid = roomid;
    this.mgr_userid = mgr_userid;
    this.mgr_nickname = mgr_nickname;
    this.requst_userid = requst_userid;
    this.ctrl = ctrl;
    this.info = info;
  }

  private PB_RS_ADDFAM_REP(Builder builder) {
    this(builder.roomid, builder.mgr_userid, builder.mgr_nickname, builder.requst_userid, builder.ctrl, builder.info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_ADDFAM_REP)) return false;
    PB_RS_ADDFAM_REP o = (PB_RS_ADDFAM_REP) other;
    return equals(roomid, o.roomid)
        && equals(mgr_userid, o.mgr_userid)
        && equals(mgr_nickname, o.mgr_nickname)
        && equals(requst_userid, o.requst_userid)
        && equals(ctrl, o.ctrl)
        && equals(info, o.info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (mgr_userid != null ? mgr_userid.hashCode() : 0);
      result = result * 37 + (mgr_nickname != null ? mgr_nickname.hashCode() : 0);
      result = result * 37 + (requst_userid != null ? requst_userid.hashCode() : 0);
      result = result * 37 + (ctrl != null ? ctrl.hashCode() : 0);
      result = result * 37 + (info != null ? info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_ADDFAM_REP> {

    public Integer roomid;
    public Long mgr_userid;
    public String mgr_nickname;
    public Long requst_userid;
    public ePB_ADDFAM_REPCMD ctrl;
    public PB_FAMILY info;

    public Builder() {
    }

    public Builder(PB_RS_ADDFAM_REP message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.mgr_userid = message.mgr_userid;
      this.mgr_nickname = message.mgr_nickname;
      this.requst_userid = message.requst_userid;
      this.ctrl = message.ctrl;
      this.info = message.info;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ����ߵ��û�ID
     */
    public Builder mgr_userid(Long mgr_userid) {
      this.mgr_userid = mgr_userid;
      return this;
    }

    /**
     * ����ߵ��ǳ�
     */
    public Builder mgr_nickname(String mgr_nickname) {
      this.mgr_nickname = mgr_nickname;
      return this;
    }

    /**
     * ��������UID
     */
    public Builder requst_userid(Long requst_userid) {
      this.requst_userid = requst_userid;
      return this;
    }

    /**
     * �ظ�����ֵ
     */
    public Builder ctrl(ePB_ADDFAM_REPCMD ctrl) {
      this.ctrl = ctrl;
      return this;
    }

    /**
     * ������Ϣ(ͬ���ʱ����������)
     */
    public Builder info(PB_FAMILY info) {
      this.info = info;
      return this;
    }

    @Override
    public PB_RS_ADDFAM_REP build() {
      checkRequiredFields();
      return new PB_RS_ADDFAM_REP(this);
    }
  }
}
