// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �����������¼Ӽ�����Ϣ
 */
public final class PB_RS_ADDFAM extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final Boolean DEFAULT_IS_REQUEST = false;
  public static final String DEFAULT_MGR_NICKNAME = "";
  public static final Integer DEFAULT_TIME = 0;

  /**
   * ���UID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �û��Ƿ����뷽
   */
  @ProtoField(tag = 2, type = BOOL, label = REQUIRED)
  public final Boolean is_request;

  /**
   * ����ߵ��ǳ�
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String mgr_nickname;

  /**
   * �¼��������û���Ϣ
   */
  @ProtoField(tag = 4, label = REQUIRED)
  public final PB_USER user;

  /**
   * ���루/������ʱ�� add by zm 2015/9/7
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer time;

  public PB_RS_ADDFAM(Long userid, Boolean is_request, String mgr_nickname, PB_USER user, Integer time) {
    this.userid = userid;
    this.is_request = is_request;
    this.mgr_nickname = mgr_nickname;
    this.user = user;
    this.time = time;
  }

  private PB_RS_ADDFAM(Builder builder) {
    this(builder.userid, builder.is_request, builder.mgr_nickname, builder.user, builder.time);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_ADDFAM)) return false;
    PB_RS_ADDFAM o = (PB_RS_ADDFAM) other;
    return equals(userid, o.userid)
        && equals(is_request, o.is_request)
        && equals(mgr_nickname, o.mgr_nickname)
        && equals(user, o.user)
        && equals(time, o.time);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (is_request != null ? is_request.hashCode() : 0);
      result = result * 37 + (mgr_nickname != null ? mgr_nickname.hashCode() : 0);
      result = result * 37 + (user != null ? user.hashCode() : 0);
      result = result * 37 + (time != null ? time.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_ADDFAM> {

    public Long userid;
    public Boolean is_request;
    public String mgr_nickname;
    public PB_USER user;
    public Integer time;

    public Builder() {
    }

    public Builder(PB_RS_ADDFAM message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.is_request = message.is_request;
      this.mgr_nickname = message.mgr_nickname;
      this.user = message.user;
      this.time = message.time;
    }

    /**
     * ���UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �û��Ƿ����뷽
     */
    public Builder is_request(Boolean is_request) {
      this.is_request = is_request;
      return this;
    }

    /**
     * ����ߵ��ǳ�
     */
    public Builder mgr_nickname(String mgr_nickname) {
      this.mgr_nickname = mgr_nickname;
      return this;
    }

    /**
     * �¼��������û���Ϣ
     */
    public Builder user(PB_USER user) {
      this.user = user;
      return this;
    }

    /**
     * ���루/������ʱ�� add by zm 2015/9/7
     */
    public Builder time(Integer time) {
      this.time = time;
      return this;
    }

    @Override
    public PB_RS_ADDFAM build() {
      checkRequiredFields();
      return new PB_RS_ADDFAM(this);
    }
  }
}
