// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ��������������ظ���Ϣ
 */
public final class PB_RS_CREATE_TALKGROUP_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_CR_TALKGROUP_Ret DEFAULT_RET = eRS_CR_TALKGROUP_Ret.eRS_CR_TG_SUC;

  /**
   * �������
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_CR_TALKGROUP_Ret ret;

  /**
   * ��������Ϣ
   */
  @ProtoField(tag = 2)
  public final PB_TALKGROUP_INFO tginfo;

  public PB_RS_CREATE_TALKGROUP_REP(eRS_CR_TALKGROUP_Ret ret, PB_TALKGROUP_INFO tginfo) {
    this.ret = ret;
    this.tginfo = tginfo;
  }

  private PB_RS_CREATE_TALKGROUP_REP(Builder builder) {
    this(builder.ret, builder.tginfo);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_CREATE_TALKGROUP_REP)) return false;
    PB_RS_CREATE_TALKGROUP_REP o = (PB_RS_CREATE_TALKGROUP_REP) other;
    return equals(ret, o.ret)
        && equals(tginfo, o.tginfo);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = ret != null ? ret.hashCode() : 0;
      result = result * 37 + (tginfo != null ? tginfo.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_CREATE_TALKGROUP_REP> {

    public eRS_CR_TALKGROUP_Ret ret;
    public PB_TALKGROUP_INFO tginfo;

    public Builder() {
    }

    public Builder(PB_RS_CREATE_TALKGROUP_REP message) {
      super(message);
      if (message == null) return;
      this.ret = message.ret;
      this.tginfo = message.tginfo;
    }

    /**
     * �������
     */
    public Builder ret(eRS_CR_TALKGROUP_Ret ret) {
      this.ret = ret;
      return this;
    }

    /**
     * ��������Ϣ
     */
    public Builder tginfo(PB_TALKGROUP_INFO tginfo) {
      this.tginfo = tginfo;
      return this;
    }

    @Override
    public PB_RS_CREATE_TALKGROUP_REP build() {
      checkRequiredFields();
      return new PB_RS_CREATE_TALKGROUP_REP(this);
    }
  }
}
