// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �������ظ��������Ա����
 */
public final class PB_RS_TG_MEMBERS extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_TGID = 0L;
  public static final Integer DEFAULT_PEOP_ALLCNT = 0;
  public static final List<PB_USER> DEFAULT_MEMBERS = Collections.emptyList();
  public static final Boolean DEFAULT_IS_END = false;
  public static final Boolean DEFAULT_IS_FIRST = false;

  /**
   * ������ID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * ��Ա������
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer peop_allcnt;

  /**
   * ��ǰ���ݰ�������ĳ�Ա��Ϣ
   */
  @ProtoField(tag = 3, label = REPEATED, messageType = PB_USER.class)
  public final List<PB_USER> members;

  /**
   * �Ƿ����һ�����ݰ�
   */
  @ProtoField(tag = 4, type = BOOL)
  public final Boolean is_end;

  /**
   * �Ƿ��ǵ�һ����
   */
  @ProtoField(tag = 5, type = BOOL)
  public final Boolean is_first;

  public PB_RS_TG_MEMBERS(Long tgid, Integer peop_allcnt, List<PB_USER> members, Boolean is_end, Boolean is_first) {
    this.tgid = tgid;
    this.peop_allcnt = peop_allcnt;
    this.members = immutableCopyOf(members);
    this.is_end = is_end;
    this.is_first = is_first;
  }

  private PB_RS_TG_MEMBERS(Builder builder) {
    this(builder.tgid, builder.peop_allcnt, builder.members, builder.is_end, builder.is_first);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_TG_MEMBERS)) return false;
    PB_RS_TG_MEMBERS o = (PB_RS_TG_MEMBERS) other;
    return equals(tgid, o.tgid)
        && equals(peop_allcnt, o.peop_allcnt)
        && equals(members, o.members)
        && equals(is_end, o.is_end)
        && equals(is_first, o.is_first);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = tgid != null ? tgid.hashCode() : 0;
      result = result * 37 + (peop_allcnt != null ? peop_allcnt.hashCode() : 0);
      result = result * 37 + (members != null ? members.hashCode() : 1);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      result = result * 37 + (is_first != null ? is_first.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_TG_MEMBERS> {

    public Long tgid;
    public Integer peop_allcnt;
    public List<PB_USER> members;
    public Boolean is_end;
    public Boolean is_first;

    public Builder() {
    }

    public Builder(PB_RS_TG_MEMBERS message) {
      super(message);
      if (message == null) return;
      this.tgid = message.tgid;
      this.peop_allcnt = message.peop_allcnt;
      this.members = copyOf(message.members);
      this.is_end = message.is_end;
      this.is_first = message.is_first;
    }

    /**
     * ������ID
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * ��Ա������
     */
    public Builder peop_allcnt(Integer peop_allcnt) {
      this.peop_allcnt = peop_allcnt;
      return this;
    }

    /**
     * ��ǰ���ݰ�������ĳ�Ա��Ϣ
     */
    public Builder members(List<PB_USER> members) {
      this.members = checkForNulls(members);
      return this;
    }

    /**
     * �Ƿ����һ�����ݰ�
     */
    public Builder is_end(Boolean is_end) {
      this.is_end = is_end;
      return this;
    }

    /**
     * �Ƿ��ǵ�һ����
     */
    public Builder is_first(Boolean is_first) {
      this.is_first = is_first;
      return this;
    }

    @Override
    public PB_RS_TG_MEMBERS build() {
      checkRequiredFields();
      return new PB_RS_TG_MEMBERS(this);
    }
  }
}
