// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * �û��б���Ϣ
 */
public final class PB_RS_USER_LIST extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ALLCOUNT = 0;
  public static final Integer DEFAULT_CURCOUNT = 0;
  public static final Boolean DEFAULT_ISEND = false;
  public static final List<PB_RS_USERINFO> DEFAULT_USERITEM = Collections.emptyList();

  @ProtoField(tag = 1, type = INT32)
  public final Integer allCount;

  @ProtoField(tag = 2, type = INT32)
  public final Integer curCount;

  @ProtoField(tag = 3, type = BOOL)
  public final Boolean isEnd;

  @ProtoField(tag = 4, label = REPEATED, messageType = PB_RS_USERINFO.class)
  public final List<PB_RS_USERINFO> userItem;

  public PB_RS_USER_LIST(Integer allCount, Integer curCount, Boolean isEnd, List<PB_RS_USERINFO> userItem) {
    this.allCount = allCount;
    this.curCount = curCount;
    this.isEnd = isEnd;
    this.userItem = immutableCopyOf(userItem);
  }

  private PB_RS_USER_LIST(Builder builder) {
    this(builder.allCount, builder.curCount, builder.isEnd, builder.userItem);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_USER_LIST)) return false;
    PB_RS_USER_LIST o = (PB_RS_USER_LIST) other;
    return equals(allCount, o.allCount)
        && equals(curCount, o.curCount)
        && equals(isEnd, o.isEnd)
        && equals(userItem, o.userItem);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = allCount != null ? allCount.hashCode() : 0;
      result = result * 37 + (curCount != null ? curCount.hashCode() : 0);
      result = result * 37 + (isEnd != null ? isEnd.hashCode() : 0);
      result = result * 37 + (userItem != null ? userItem.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_USER_LIST> {

    public Integer allCount;
    public Integer curCount;
    public Boolean isEnd;
    public List<PB_RS_USERINFO> userItem;

    public Builder() {
    }

    public Builder(PB_RS_USER_LIST message) {
      super(message);
      if (message == null) return;
      this.allCount = message.allCount;
      this.curCount = message.curCount;
      this.isEnd = message.isEnd;
      this.userItem = copyOf(message.userItem);
    }

    public Builder allCount(Integer allCount) {
      this.allCount = allCount;
      return this;
    }

    public Builder curCount(Integer curCount) {
      this.curCount = curCount;
      return this;
    }

    public Builder isEnd(Boolean isEnd) {
      this.isEnd = isEnd;
      return this;
    }

    public Builder userItem(List<PB_RS_USERINFO> userItem) {
      this.userItem = checkForNulls(userItem);
      return this;
    }

    @Override
    public PB_RS_USER_LIST build() {
      return new PB_RS_USER_LIST(this);
    }
  }
}
