// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �û���ʾ��Ϣ
 */
public final class PB_RS_USER_DSP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final String DEFAULT_HEADURL = "";
  public static final Long DEFAULT_PRETTYNUM = 0L;
  public static final ePB_COM_JOB DEFAULT_JOB = ePB_COM_JOB.PLAYER;
  public static final Integer DEFAULT_VIP = 0;
  public static final Integer DEFAULT_ROOMID = 0;

  /**
   * �û�id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �û��س�
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String nickname;

  /**
   * ͷ��
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String headurl;

  /**
   * ����
   */
  @ProtoField(tag = 4, type = INT64)
  public final Long prettynum;

  /**
   * ְҵ
   */
  @ProtoField(tag = 5, type = ENUM)
  public final ePB_COM_JOB job;

  /**
   * VIP
   */
  @ProtoField(tag = 6, type = INT32)
  public final Integer vip;

  /**
   * ����ID
   */
  @ProtoField(tag = 7, type = INT32)
  public final Integer roomid;

  public PB_RS_USER_DSP(Long userid, String nickname, String headurl, Long prettynum, ePB_COM_JOB job, Integer vip, Integer roomid) {
    this.userid = userid;
    this.nickname = nickname;
    this.headurl = headurl;
    this.prettynum = prettynum;
    this.job = job;
    this.vip = vip;
    this.roomid = roomid;
  }

  private PB_RS_USER_DSP(Builder builder) {
    this(builder.userid, builder.nickname, builder.headurl, builder.prettynum, builder.job, builder.vip, builder.roomid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_USER_DSP)) return false;
    PB_RS_USER_DSP o = (PB_RS_USER_DSP) other;
    return equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(headurl, o.headurl)
        && equals(prettynum, o.prettynum)
        && equals(job, o.job)
        && equals(vip, o.vip)
        && equals(roomid, o.roomid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (headurl != null ? headurl.hashCode() : 0);
      result = result * 37 + (prettynum != null ? prettynum.hashCode() : 0);
      result = result * 37 + (job != null ? job.hashCode() : 0);
      result = result * 37 + (vip != null ? vip.hashCode() : 0);
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_USER_DSP> {

    public Long userid;
    public String nickname;
    public String headurl;
    public Long prettynum;
    public ePB_COM_JOB job;
    public Integer vip;
    public Integer roomid;

    public Builder() {
    }

    public Builder(PB_RS_USER_DSP message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.headurl = message.headurl;
      this.prettynum = message.prettynum;
      this.job = message.job;
      this.vip = message.vip;
      this.roomid = message.roomid;
    }

    /**
     * �û�id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �û��س�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * ͷ��
     */
    public Builder headurl(String headurl) {
      this.headurl = headurl;
      return this;
    }

    /**
     * ����
     */
    public Builder prettynum(Long prettynum) {
      this.prettynum = prettynum;
      return this;
    }

    /**
     * ְҵ
     */
    public Builder job(ePB_COM_JOB job) {
      this.job = job;
      return this;
    }

    /**
     * VIP
     */
    public Builder vip(Integer vip) {
      this.vip = vip;
      return this;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    @Override
    public PB_RS_USER_DSP build() {
      checkRequiredFields();
      return new PB_RS_USER_DSP(this);
    }
  }
}
