// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

/**
 * �û���Ϣ
 */
public final class PB_RS_USERINFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_SORTNUM = 0;

  /**
   * �б������
   */
  @ProtoField(tag = 1, type = INT32)
  public final Integer sortNum;

  /**
   * ������Ϣ
   */
  @ProtoField(tag = 2)
  public final PB_RS_USER_BASIC user_basic;

  public PB_RS_USERINFO(Integer sortNum, PB_RS_USER_BASIC user_basic) {
    this.sortNum = sortNum;
    this.user_basic = user_basic;
  }

  private PB_RS_USERINFO(Builder builder) {
    this(builder.sortNum, builder.user_basic);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_USERINFO)) return false;
    PB_RS_USERINFO o = (PB_RS_USERINFO) other;
    return equals(sortNum, o.sortNum)
        && equals(user_basic, o.user_basic);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = sortNum != null ? sortNum.hashCode() : 0;
      result = result * 37 + (user_basic != null ? user_basic.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_USERINFO> {

    public Integer sortNum;
    public PB_RS_USER_BASIC user_basic;

    public Builder() {
    }

    public Builder(PB_RS_USERINFO message) {
      super(message);
      if (message == null) return;
      this.sortNum = message.sortNum;
      this.user_basic = message.user_basic;
    }

    /**
     * �б������
     */
    public Builder sortNum(Integer sortNum) {
      this.sortNum = sortNum;
      return this;
    }

    /**
     * ������Ϣ
     */
    public Builder user_basic(PB_RS_USER_BASIC user_basic) {
      this.user_basic = user_basic;
      return this;
    }

    @Override
    public PB_RS_USERINFO build() {
      return new PB_RS_USERINFO(this);
    }
  }
}
