// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������������Ϣ�ظ�
 */
public final class PB_RS_SEND_CHAT_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_SendChat_Ret DEFAULT_RET = eRS_SendChat_Ret.RS_SC_SUCC;
  public static final Integer DEFAULT_MSG_INDEX = 0;
  public static final ePB_CHAT_ZONE DEFAULT_CHATZONE = ePB_CHAT_ZONE.CM_ZONE_FAM_NORMAL;
  public static final Long DEFAULT_TARGETID = 0L;
  public static final Long DEFAULT_MSG_ID = 0L;
  public static final Long DEFAULT_SEND_TIME = 0L;
  public static final ePB_MSG_TYPE DEFAULT_TYPE = ePB_MSG_TYPE.MSG_TYPE_SYSMSG;

  /**
   * ���
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_SendChat_Ret ret;

  /**
   * �ͻ�����Ϣ���
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer msg_index;

  /**
   * ��Ϣ����
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final ePB_CHAT_ZONE chatzone;

  /**
   * Ŀ��ID���û�ID,����ID,������ID...)
   */
  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long targetid;

  /**
   * �ɹ�������������
   * ��Ϣ���
   */
  @ProtoField(tag = 5, type = INT64)
  public final Long msg_id;

  /**
   * ����ʱ��
   */
  @ProtoField(tag = 6, type = INT64)
  public final Long send_time;

  /**
   * ��Ϣ����
   */
  @ProtoField(tag = 7, type = ENUM)
  public final ePB_MSG_TYPE type;

  public PB_RS_SEND_CHAT_REP(eRS_SendChat_Ret ret, Integer msg_index, ePB_CHAT_ZONE chatzone, Long targetid, Long msg_id, Long send_time, ePB_MSG_TYPE type) {
    this.ret = ret;
    this.msg_index = msg_index;
    this.chatzone = chatzone;
    this.targetid = targetid;
    this.msg_id = msg_id;
    this.send_time = send_time;
    this.type = type;
  }

  private PB_RS_SEND_CHAT_REP(Builder builder) {
    this(builder.ret, builder.msg_index, builder.chatzone, builder.targetid, builder.msg_id, builder.send_time, builder.type);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_SEND_CHAT_REP)) return false;
    PB_RS_SEND_CHAT_REP o = (PB_RS_SEND_CHAT_REP) other;
    return equals(ret, o.ret)
        && equals(msg_index, o.msg_index)
        && equals(chatzone, o.chatzone)
        && equals(targetid, o.targetid)
        && equals(msg_id, o.msg_id)
        && equals(send_time, o.send_time)
        && equals(type, o.type);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = ret != null ? ret.hashCode() : 0;
      result = result * 37 + (msg_index != null ? msg_index.hashCode() : 0);
      result = result * 37 + (chatzone != null ? chatzone.hashCode() : 0);
      result = result * 37 + (targetid != null ? targetid.hashCode() : 0);
      result = result * 37 + (msg_id != null ? msg_id.hashCode() : 0);
      result = result * 37 + (send_time != null ? send_time.hashCode() : 0);
      result = result * 37 + (type != null ? type.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_SEND_CHAT_REP> {

    public eRS_SendChat_Ret ret;
    public Integer msg_index;
    public ePB_CHAT_ZONE chatzone;
    public Long targetid;
    public Long msg_id;
    public Long send_time;
    public ePB_MSG_TYPE type;

    public Builder() {
    }

    public Builder(PB_RS_SEND_CHAT_REP message) {
      super(message);
      if (message == null) return;
      this.ret = message.ret;
      this.msg_index = message.msg_index;
      this.chatzone = message.chatzone;
      this.targetid = message.targetid;
      this.msg_id = message.msg_id;
      this.send_time = message.send_time;
      this.type = message.type;
    }

    /**
     * ���
     */
    public Builder ret(eRS_SendChat_Ret ret) {
      this.ret = ret;
      return this;
    }

    /**
     * �ͻ�����Ϣ���
     */
    public Builder msg_index(Integer msg_index) {
      this.msg_index = msg_index;
      return this;
    }

    /**
     * ��Ϣ����
     */
    public Builder chatzone(ePB_CHAT_ZONE chatzone) {
      this.chatzone = chatzone;
      return this;
    }

    /**
     * Ŀ��ID���û�ID,����ID,������ID...)
     */
    public Builder targetid(Long targetid) {
      this.targetid = targetid;
      return this;
    }

    /**
     * �ɹ�������������
     * ��Ϣ���
     */
    public Builder msg_id(Long msg_id) {
      this.msg_id = msg_id;
      return this;
    }

    /**
     * ����ʱ��
     */
    public Builder send_time(Long send_time) {
      this.send_time = send_time;
      return this;
    }

    /**
     * ��Ϣ����
     */
    public Builder type(ePB_MSG_TYPE type) {
      this.type = type;
      return this;
    }

    @Override
    public PB_RS_SEND_CHAT_REP build() {
      checkRequiredFields();
      return new PB_RS_SEND_CHAT_REP(this);
    }
  }
}
