// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_RS_USER_CHAT extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_MSG_ID = 0L;

  /**
   * �������Ϣ���
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long msg_id;

  /**
   * ��Ϣ����
   */
  @ProtoField(tag = 2)
  public final PB_CHAT_MSG msginfo;

  public PB_RS_USER_CHAT(Long msg_id, PB_CHAT_MSG msginfo) {
    this.msg_id = msg_id;
    this.msginfo = msginfo;
  }

  private PB_RS_USER_CHAT(Builder builder) {
    this(builder.msg_id, builder.msginfo);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_USER_CHAT)) return false;
    PB_RS_USER_CHAT o = (PB_RS_USER_CHAT) other;
    return equals(msg_id, o.msg_id)
        && equals(msginfo, o.msginfo);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = msg_id != null ? msg_id.hashCode() : 0;
      result = result * 37 + (msginfo != null ? msginfo.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_USER_CHAT> {

    public Long msg_id;
    public PB_CHAT_MSG msginfo;

    public Builder() {
    }

    public Builder(PB_RS_USER_CHAT message) {
      super(message);
      if (message == null) return;
      this.msg_id = message.msg_id;
      this.msginfo = message.msginfo;
    }

    /**
     * �������Ϣ���
     */
    public Builder msg_id(Long msg_id) {
      this.msg_id = msg_id;
      return this;
    }

    /**
     * ��Ϣ����
     */
    public Builder msginfo(PB_CHAT_MSG msginfo) {
      this.msginfo = msginfo;
      return this;
    }

    @Override
    public PB_RS_USER_CHAT build() {
      checkRequiredFields();
      return new PB_RS_USER_CHAT(this);
    }
  }
}
