// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ��ȡ�ҵ��������б�
 */
public final class PB_RS_TALKGROUP_LIST extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ALLCNT = 0;
  public static final List<PB_TALKGROUP_INFO> DEFAULT_ITEMS = Collections.emptyList();
  public static final Boolean DEFAULT_IS_END = false;

  /**
   * ����
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer allcnt;

  /**
   * �������б�
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = PB_TALKGROUP_INFO.class)
  public final List<PB_TALKGROUP_INFO> items;

  /**
   * �Ƿ����һ�����ݰ�
   */
  @ProtoField(tag = 3, type = BOOL, label = REQUIRED)
  public final Boolean is_end;

  public PB_RS_TALKGROUP_LIST(Integer allcnt, List<PB_TALKGROUP_INFO> items, Boolean is_end) {
    this.allcnt = allcnt;
    this.items = immutableCopyOf(items);
    this.is_end = is_end;
  }

  private PB_RS_TALKGROUP_LIST(Builder builder) {
    this(builder.allcnt, builder.items, builder.is_end);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_TALKGROUP_LIST)) return false;
    PB_RS_TALKGROUP_LIST o = (PB_RS_TALKGROUP_LIST) other;
    return equals(allcnt, o.allcnt)
        && equals(items, o.items)
        && equals(is_end, o.is_end);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = allcnt != null ? allcnt.hashCode() : 0;
      result = result * 37 + (items != null ? items.hashCode() : 1);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_TALKGROUP_LIST> {

    public Integer allcnt;
    public List<PB_TALKGROUP_INFO> items;
    public Boolean is_end;

    public Builder() {
    }

    public Builder(PB_RS_TALKGROUP_LIST message) {
      super(message);
      if (message == null) return;
      this.allcnt = message.allcnt;
      this.items = copyOf(message.items);
      this.is_end = message.is_end;
    }

    /**
     * ����
     */
    public Builder allcnt(Integer allcnt) {
      this.allcnt = allcnt;
      return this;
    }

    /**
     * �������б�
     */
    public Builder items(List<PB_TALKGROUP_INFO> items) {
      this.items = checkForNulls(items);
      return this;
    }

    /**
     * �Ƿ����һ�����ݰ�
     */
    public Builder is_end(Boolean is_end) {
      this.is_end = is_end;
      return this;
    }

    @Override
    public PB_RS_TALKGROUP_LIST build() {
      checkRequiredFields();
      return new PB_RS_TALKGROUP_LIST(this);
    }
  }
}
