// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_RS_NOTICE_MSGLIST extends Message {
  private static final long serialVersionUID = 0L;

  public static final eNOTICE_MSG_TYPE DEFAULT_NOTICETYPE = eNOTICE_MSG_TYPE.NOTICE_MSG_TYPE_FRD;
  public static final Integer DEFAULT_ALLCNT = 0;
  public static final List<PB_NOTICE_MSG> DEFAULT_ITEMS = Collections.emptyList();
  public static final Boolean DEFAULT_IS_END = false;

  /**
   * ֪ͨ����
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eNOTICE_MSG_TYPE noticeType;

  /**
   * ��Ϣ����
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer allcnt;

  /**
   * ֪ͨ��Ϣ����
   */
  @ProtoField(tag = 3, label = REPEATED, messageType = PB_NOTICE_MSG.class)
  public final List<PB_NOTICE_MSG> items;

  /**
   * �Ƿ����һ�����ݰ�
   */
  @ProtoField(tag = 4, type = BOOL, label = REQUIRED)
  public final Boolean is_end;

  public PB_RS_NOTICE_MSGLIST(eNOTICE_MSG_TYPE noticeType, Integer allcnt, List<PB_NOTICE_MSG> items, Boolean is_end) {
    this.noticeType = noticeType;
    this.allcnt = allcnt;
    this.items = immutableCopyOf(items);
    this.is_end = is_end;
  }

  private PB_RS_NOTICE_MSGLIST(Builder builder) {
    this(builder.noticeType, builder.allcnt, builder.items, builder.is_end);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_NOTICE_MSGLIST)) return false;
    PB_RS_NOTICE_MSGLIST o = (PB_RS_NOTICE_MSGLIST) other;
    return equals(noticeType, o.noticeType)
        && equals(allcnt, o.allcnt)
        && equals(items, o.items)
        && equals(is_end, o.is_end);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = noticeType != null ? noticeType.hashCode() : 0;
      result = result * 37 + (allcnt != null ? allcnt.hashCode() : 0);
      result = result * 37 + (items != null ? items.hashCode() : 1);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_NOTICE_MSGLIST> {

    public eNOTICE_MSG_TYPE noticeType;
    public Integer allcnt;
    public List<PB_NOTICE_MSG> items;
    public Boolean is_end;

    public Builder() {
    }

    public Builder(PB_RS_NOTICE_MSGLIST message) {
      super(message);
      if (message == null) return;
      this.noticeType = message.noticeType;
      this.allcnt = message.allcnt;
      this.items = copyOf(message.items);
      this.is_end = message.is_end;
    }

    /**
     * ֪ͨ����
     */
    public Builder noticeType(eNOTICE_MSG_TYPE noticeType) {
      this.noticeType = noticeType;
      return this;
    }

    /**
     * ��Ϣ����
     */
    public Builder allcnt(Integer allcnt) {
      this.allcnt = allcnt;
      return this;
    }

    /**
     * ֪ͨ��Ϣ����
     */
    public Builder items(List<PB_NOTICE_MSG> items) {
      this.items = checkForNulls(items);
      return this;
    }

    /**
     * �Ƿ����һ�����ݰ�
     */
    public Builder is_end(Boolean is_end) {
      this.is_end = is_end;
      return this;
    }

    @Override
    public PB_RS_NOTICE_MSGLIST build() {
      checkRequiredFields();
      return new PB_RS_NOTICE_MSGLIST(this);
    }
  }
}
