// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * server send client exit room msg
 * add 2014/6/10
 */
public final class PB_RS_EXITROOM extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;

  /**
   * ��ҽ�ɫUID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  public PB_RS_EXITROOM(Long userid) {
    this.userid = userid;
  }

  private PB_RS_EXITROOM(Builder builder) {
    this(builder.userid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_EXITROOM)) return false;
    return equals(userid, ((PB_RS_EXITROOM) other).userid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = userid != null ? userid.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<PB_RS_EXITROOM> {

    public Long userid;

    public Builder() {
    }

    public Builder(PB_RS_EXITROOM message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
    }

    /**
     * ��ҽ�ɫUID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    @Override
    public PB_RS_EXITROOM build() {
      checkRequiredFields();
      return new PB_RS_EXITROOM(this);
    }
  }
}
