// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_RS_FAMILY_RET extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final Long DEFAULT_FROMID = 0L;
  public static final Integer DEFAULT_APPLYID = 0;
  public static final eRS_RelateFamily_Ret DEFAULT_FAMILY_RET = eRS_RelateFamily_Ret.RS_RF_SUCC;

  /**
   * ����������ظ������ߵĽṹ
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer familyid;

  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long fromid;

  /**
   * ������Ϣid
   */
  @ProtoField(tag = 4, type = INT32, label = REQUIRED)
  public final Integer applyid;

  /**
   * ���ش�������
   */
  @ProtoField(tag = 5, type = ENUM, label = REQUIRED)
  public final eRS_RelateFamily_Ret family_ret;

  public PB_RS_FAMILY_RET(Integer roomid, Integer familyid, Long fromid, Integer applyid, eRS_RelateFamily_Ret family_ret) {
    this.roomid = roomid;
    this.familyid = familyid;
    this.fromid = fromid;
    this.applyid = applyid;
    this.family_ret = family_ret;
  }

  private PB_RS_FAMILY_RET(Builder builder) {
    this(builder.roomid, builder.familyid, builder.fromid, builder.applyid, builder.family_ret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_FAMILY_RET)) return false;
    PB_RS_FAMILY_RET o = (PB_RS_FAMILY_RET) other;
    return equals(roomid, o.roomid)
        && equals(familyid, o.familyid)
        && equals(fromid, o.fromid)
        && equals(applyid, o.applyid)
        && equals(family_ret, o.family_ret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (fromid != null ? fromid.hashCode() : 0);
      result = result * 37 + (applyid != null ? applyid.hashCode() : 0);
      result = result * 37 + (family_ret != null ? family_ret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_FAMILY_RET> {

    public Integer roomid;
    public Integer familyid;
    public Long fromid;
    public Integer applyid;
    public eRS_RelateFamily_Ret family_ret;

    public Builder() {
    }

    public Builder(PB_RS_FAMILY_RET message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.familyid = message.familyid;
      this.fromid = message.fromid;
      this.applyid = message.applyid;
      this.family_ret = message.family_ret;
    }

    /**
     * ����������ظ������ߵĽṹ
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    public Builder fromid(Long fromid) {
      this.fromid = fromid;
      return this;
    }

    /**
     * ������Ϣid
     */
    public Builder applyid(Integer applyid) {
      this.applyid = applyid;
      return this;
    }

    /**
     * ���ش�������
     */
    public Builder family_ret(eRS_RelateFamily_Ret family_ret) {
      this.family_ret = family_ret;
      return this;
    }

    @Override
    public PB_RS_FAMILY_RET build() {
      checkRequiredFields();
      return new PB_RS_FAMILY_RET(this);
    }
  }
}
