// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ���������û��б�(�û���Ļ����ᷢ�Ͷ����)
 */
public final class PB_RS_AFAMQ_LIST extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final Boolean DEFAULT_SUCC = false;
  public static final Boolean DEFAULT_END = false;
  public static final List<PB_AFAMQ_INFO> DEFAULT_ITEMS = Collections.emptyList();
  public static final Integer DEFAULT_UNREAD = 0;

  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ��ȡ�Ƿ�ɹ�
   */
  @ProtoField(tag = 2, type = BOOL, label = REQUIRED)
  public final Boolean succ;

  /**
   * �Ƿ����һ��
   */
  @ProtoField(tag = 3, type = BOOL, label = REQUIRED)
  public final Boolean end;

  /**
   * �û�������Ϣ����
   */
  @ProtoField(tag = 4, label = REPEATED, messageType = PB_AFAMQ_INFO.class)
  public final List<PB_AFAMQ_INFO> items;

  /**
   * δ���� add 2014/11/17
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer unread;

  public PB_RS_AFAMQ_LIST(Long userid, Boolean succ, Boolean end, List<PB_AFAMQ_INFO> items, Integer unread) {
    this.userid = userid;
    this.succ = succ;
    this.end = end;
    this.items = immutableCopyOf(items);
    this.unread = unread;
  }

  private PB_RS_AFAMQ_LIST(Builder builder) {
    this(builder.userid, builder.succ, builder.end, builder.items, builder.unread);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_AFAMQ_LIST)) return false;
    PB_RS_AFAMQ_LIST o = (PB_RS_AFAMQ_LIST) other;
    return equals(userid, o.userid)
        && equals(succ, o.succ)
        && equals(end, o.end)
        && equals(items, o.items)
        && equals(unread, o.unread);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (succ != null ? succ.hashCode() : 0);
      result = result * 37 + (end != null ? end.hashCode() : 0);
      result = result * 37 + (items != null ? items.hashCode() : 1);
      result = result * 37 + (unread != null ? unread.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_AFAMQ_LIST> {

    public Long userid;
    public Boolean succ;
    public Boolean end;
    public List<PB_AFAMQ_INFO> items;
    public Integer unread;

    public Builder() {
    }

    public Builder(PB_RS_AFAMQ_LIST message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.succ = message.succ;
      this.end = message.end;
      this.items = copyOf(message.items);
      this.unread = message.unread;
    }

    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ��ȡ�Ƿ�ɹ�
     */
    public Builder succ(Boolean succ) {
      this.succ = succ;
      return this;
    }

    /**
     * �Ƿ����һ��
     */
    public Builder end(Boolean end) {
      this.end = end;
      return this;
    }

    /**
     * �û�������Ϣ����
     */
    public Builder items(List<PB_AFAMQ_INFO> items) {
      this.items = checkForNulls(items);
      return this;
    }

    /**
     * δ���� add 2014/11/17
     */
    public Builder unread(Integer unread) {
      this.unread = unread;
      return this;
    }

    @Override
    public PB_RS_AFAMQ_LIST build() {
      checkRequiredFields();
      return new PB_RS_AFAMQ_LIST(this);
    }
  }
}
