// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ����������Ϣ
 */
public final class PB_RS_ROOM_PEONUM extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_TOTLENUM = 0;
  public static final Integer DEFAULT_MGRNUM = 0;
  public static final Integer DEFAULT_USERNUM = 0;

  /**
   * ����������
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer totleNum;

  /**
   * ����Ա����
   */
  @ProtoField(tag = 2, type = INT32)
  public final Integer mgrNum;

  /**
   * �û�����
   */
  @ProtoField(tag = 3, type = INT32)
  public final Integer userNum;

  public PB_RS_ROOM_PEONUM(Integer totleNum, Integer mgrNum, Integer userNum) {
    this.totleNum = totleNum;
    this.mgrNum = mgrNum;
    this.userNum = userNum;
  }

  private PB_RS_ROOM_PEONUM(Builder builder) {
    this(builder.totleNum, builder.mgrNum, builder.userNum);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_ROOM_PEONUM)) return false;
    PB_RS_ROOM_PEONUM o = (PB_RS_ROOM_PEONUM) other;
    return equals(totleNum, o.totleNum)
        && equals(mgrNum, o.mgrNum)
        && equals(userNum, o.userNum);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = totleNum != null ? totleNum.hashCode() : 0;
      result = result * 37 + (mgrNum != null ? mgrNum.hashCode() : 0);
      result = result * 37 + (userNum != null ? userNum.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_ROOM_PEONUM> {

    public Integer totleNum;
    public Integer mgrNum;
    public Integer userNum;

    public Builder() {
    }

    public Builder(PB_RS_ROOM_PEONUM message) {
      super(message);
      if (message == null) return;
      this.totleNum = message.totleNum;
      this.mgrNum = message.mgrNum;
      this.userNum = message.userNum;
    }

    /**
     * ����������
     */
    public Builder totleNum(Integer totleNum) {
      this.totleNum = totleNum;
      return this;
    }

    /**
     * ����Ա����
     */
    public Builder mgrNum(Integer mgrNum) {
      this.mgrNum = mgrNum;
      return this;
    }

    /**
     * �û�����
     */
    public Builder userNum(Integer userNum) {
      this.userNum = userNum;
      return this;
    }

    @Override
    public PB_RS_ROOM_PEONUM build() {
      checkRequiredFields();
      return new PB_RS_ROOM_PEONUM(this);
    }
  }
}
