// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �����ͻ��˵ķ�����Ϣ
 */
public final class PB_RS_ROOM_INFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Integer DEFAULT_ONLINEPEO = 0;

  /**
   * room id
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * people num online
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer onlinePeo;

  public PB_RS_ROOM_INFO(Integer roomid, Integer onlinePeo) {
    this.roomid = roomid;
    this.onlinePeo = onlinePeo;
  }

  private PB_RS_ROOM_INFO(Builder builder) {
    this(builder.roomid, builder.onlinePeo);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_ROOM_INFO)) return false;
    PB_RS_ROOM_INFO o = (PB_RS_ROOM_INFO) other;
    return equals(roomid, o.roomid)
        && equals(onlinePeo, o.onlinePeo);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (onlinePeo != null ? onlinePeo.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_ROOM_INFO> {

    public Integer roomid;
    public Integer onlinePeo;

    public Builder() {
    }

    public Builder(PB_RS_ROOM_INFO message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.onlinePeo = message.onlinePeo;
    }

    /**
     * room id
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * people num online
     */
    public Builder onlinePeo(Integer onlinePeo) {
      this.onlinePeo = onlinePeo;
      return this;
    }

    @Override
    public PB_RS_ROOM_INFO build() {
      checkRequiredFields();
      return new PB_RS_ROOM_INFO(this);
    }
  }
}
