// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �����������¼Ӽ���ʧ����Ϣ
 */
public final class PB_RS_ADDFAM_FAIL extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_REQUST_USERID = 0L;
  public static final Long DEFAULT_MGR_USERID = 0L;
  public static final Integer DEFAULT_RETCODE = 0;

  /**
   * �����UID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long requst_userid;

  /**
   * ����ߵ�UID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long mgr_userid;

  /**
   * ������
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer retcode;

  public PB_RS_ADDFAM_FAIL(Long requst_userid, Long mgr_userid, Integer retcode) {
    this.requst_userid = requst_userid;
    this.mgr_userid = mgr_userid;
    this.retcode = retcode;
  }

  private PB_RS_ADDFAM_FAIL(Builder builder) {
    this(builder.requst_userid, builder.mgr_userid, builder.retcode);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_RS_ADDFAM_FAIL)) return false;
    PB_RS_ADDFAM_FAIL o = (PB_RS_ADDFAM_FAIL) other;
    return equals(requst_userid, o.requst_userid)
        && equals(mgr_userid, o.mgr_userid)
        && equals(retcode, o.retcode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = requst_userid != null ? requst_userid.hashCode() : 0;
      result = result * 37 + (mgr_userid != null ? mgr_userid.hashCode() : 0);
      result = result * 37 + (retcode != null ? retcode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_RS_ADDFAM_FAIL> {

    public Long requst_userid;
    public Long mgr_userid;
    public Integer retcode;

    public Builder() {
    }

    public Builder(PB_RS_ADDFAM_FAIL message) {
      super(message);
      if (message == null) return;
      this.requst_userid = message.requst_userid;
      this.mgr_userid = message.mgr_userid;
      this.retcode = message.retcode;
    }

    /**
     * �����UID
     */
    public Builder requst_userid(Long requst_userid) {
      this.requst_userid = requst_userid;
      return this;
    }

    /**
     * ����ߵ�UID
     */
    public Builder mgr_userid(Long mgr_userid) {
      this.mgr_userid = mgr_userid;
      return this;
    }

    /**
     * ������
     */
    public Builder retcode(Integer retcode) {
      this.retcode = retcode;
      return this;
    }

    @Override
    public PB_RS_ADDFAM_FAIL build() {
      checkRequiredFields();
      return new PB_RS_ADDFAM_FAIL(this);
    }
  }
}
