// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ���ú�����
 */
public final class PB_SET_BLACK extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_ACCOUNT = "";
  public static final eRS_BLACK_ZONE DEFAULT_ZONE = eRS_BLACK_ZONE.eRS_BLACK_SET;

  /**
   * ������id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ����Ϊ���������˺�
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String account;

  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_BLACK_ZONE zone;

  public PB_SET_BLACK(Long userid, String account, eRS_BLACK_ZONE zone) {
    this.userid = userid;
    this.account = account;
    this.zone = zone;
  }

  private PB_SET_BLACK(Builder builder) {
    this(builder.userid, builder.account, builder.zone);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_SET_BLACK)) return false;
    PB_SET_BLACK o = (PB_SET_BLACK) other;
    return equals(userid, o.userid)
        && equals(account, o.account)
        && equals(zone, o.zone);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (zone != null ? zone.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_SET_BLACK> {

    public Long userid;
    public String account;
    public eRS_BLACK_ZONE zone;

    public Builder() {
    }

    public Builder(PB_SET_BLACK message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.account = message.account;
      this.zone = message.zone;
    }

    /**
     * ������id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ����Ϊ���������˺�
     */
    public Builder account(String account) {
      this.account = account;
      return this;
    }

    public Builder zone(eRS_BLACK_ZONE zone) {
      this.zone = zone;
      return this;
    }

    @Override
    public PB_SET_BLACK build() {
      checkRequiredFields();
      return new PB_SET_BLACK(this);
    }
  }
}
