// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������֪ͨ��Ϣ
 */
public final class PB_TALKGROUP_NOTICE extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_TITLE = "";
  public static final String DEFAULT_CONTENT = "";
  public static final String DEFAULT_ICONURL = "";
  public static final Integer DEFAULT_TIME = 0;

  /**
   * ����
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String title;

  /**
   * ����
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String content;

  /**
   * ͼ��
   */
  @ProtoField(tag = 3, type = STRING)
  public final String iconurl;

  /**
   * ����ʱ��
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer time;

  public PB_TALKGROUP_NOTICE(String title, String content, String iconurl, Integer time) {
    this.title = title;
    this.content = content;
    this.iconurl = iconurl;
    this.time = time;
  }

  private PB_TALKGROUP_NOTICE(Builder builder) {
    this(builder.title, builder.content, builder.iconurl, builder.time);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_TALKGROUP_NOTICE)) return false;
    PB_TALKGROUP_NOTICE o = (PB_TALKGROUP_NOTICE) other;
    return equals(title, o.title)
        && equals(content, o.content)
        && equals(iconurl, o.iconurl)
        && equals(time, o.time);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = title != null ? title.hashCode() : 0;
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (iconurl != null ? iconurl.hashCode() : 0);
      result = result * 37 + (time != null ? time.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_TALKGROUP_NOTICE> {

    public String title;
    public String content;
    public String iconurl;
    public Integer time;

    public Builder() {
    }

    public Builder(PB_TALKGROUP_NOTICE message) {
      super(message);
      if (message == null) return;
      this.title = message.title;
      this.content = message.content;
      this.iconurl = message.iconurl;
      this.time = message.time;
    }

    /**
     * ����
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    /**
     * ����
     */
    public Builder content(String content) {
      this.content = content;
      return this;
    }

    /**
     * ͼ��
     */
    public Builder iconurl(String iconurl) {
      this.iconurl = iconurl;
      return this;
    }

    /**
     * ����ʱ��
     */
    public Builder time(Integer time) {
      this.time = time;
      return this;
    }

    @Override
    public PB_TALKGROUP_NOTICE build() {
      checkRequiredFields();
      return new PB_TALKGROUP_NOTICE(this);
    }
  }
}
