// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ����Ӻ���
 */
public final class PB_USER_ADDFRD_REQ extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_TO_USERID = 0L;
  public static final String DEFAULT_TO_ACCOUNT = "";
  public static final String DEFAULT_DEMOTEXT = "";

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * UID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * Ŀ��UID
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long to_userid;

  /**
   * Ŀ��UID
   */
  @ProtoField(tag = 4, type = STRING)
  public final String to_account;

  /**
   * Ŀ���û�JSON��Ϣ APPIDΪ100ʱ��д
   */
  @ProtoField(tag = 5, type = STRING)
  public final String demotext;

  public PB_USER_ADDFRD_REQ(Integer roomid, Long userid, Long to_userid, String to_account, String demotext) {
    this.roomid = roomid;
    this.userid = userid;
    this.to_userid = to_userid;
    this.to_account = to_account;
    this.demotext = demotext;
  }

  private PB_USER_ADDFRD_REQ(Builder builder) {
    this(builder.roomid, builder.userid, builder.to_userid, builder.to_account, builder.demotext);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_ADDFRD_REQ)) return false;
    PB_USER_ADDFRD_REQ o = (PB_USER_ADDFRD_REQ) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(to_userid, o.to_userid)
        && equals(to_account, o.to_account)
        && equals(demotext, o.demotext);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (to_userid != null ? to_userid.hashCode() : 0);
      result = result * 37 + (to_account != null ? to_account.hashCode() : 0);
      result = result * 37 + (demotext != null ? demotext.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_ADDFRD_REQ> {

    public Integer roomid;
    public Long userid;
    public Long to_userid;
    public String to_account;
    public String demotext;

    public Builder() {
    }

    public Builder(PB_USER_ADDFRD_REQ message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.to_userid = message.to_userid;
      this.to_account = message.to_account;
      this.demotext = message.demotext;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * Ŀ��UID
     */
    public Builder to_userid(Long to_userid) {
      this.to_userid = to_userid;
      return this;
    }

    /**
     * Ŀ��UID
     */
    public Builder to_account(String to_account) {
      this.to_account = to_account;
      return this;
    }

    /**
     * Ŀ���û�JSON��Ϣ APPIDΪ100ʱ��д
     */
    public Builder demotext(String demotext) {
      this.demotext = demotext;
      return this;
    }

    @Override
    public PB_USER_ADDFRD_REQ build() {
      checkRequiredFields();
      return new PB_USER_ADDFRD_REQ(this);
    }
  }
}
