// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ���������������ظ�
 */
public final class PB_USER_ADDFAM_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final String DEFAULT_NICKNAME = "";
  public static final Long DEFAULT_REQUST_USERID = 0L;
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final Integer DEFAULT_APPLYID = 0;
  public static final ePB_ADDFAM_REPCMD DEFAULT_CTRL = ePB_ADDFAM_REPCMD.AFM_ACCEPT;

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * ����ߵ�UID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ����ߵ��ǳ�
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public final String nickname;

  /**
   * �����UID
   */
  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public final Long requst_userid;

  /**
   * ����ID
   */
  @ProtoField(tag = 5, type = INT32, label = REQUIRED)
  public final Integer familyid;

  /**
   * ������Ϣid
   */
  @ProtoField(tag = 6, type = INT32, label = REQUIRED)
  public final Integer applyid;

  /**
   * �ظ�����
   */
  @ProtoField(tag = 7, type = ENUM, label = REQUIRED)
  public final ePB_ADDFAM_REPCMD ctrl;

  public PB_USER_ADDFAM_REP(Integer roomid, Long userid, String nickname, Long requst_userid, Integer familyid, Integer applyid, ePB_ADDFAM_REPCMD ctrl) {
    this.roomid = roomid;
    this.userid = userid;
    this.nickname = nickname;
    this.requst_userid = requst_userid;
    this.familyid = familyid;
    this.applyid = applyid;
    this.ctrl = ctrl;
  }

  private PB_USER_ADDFAM_REP(Builder builder) {
    this(builder.roomid, builder.userid, builder.nickname, builder.requst_userid, builder.familyid, builder.applyid, builder.ctrl);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_ADDFAM_REP)) return false;
    PB_USER_ADDFAM_REP o = (PB_USER_ADDFAM_REP) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(nickname, o.nickname)
        && equals(requst_userid, o.requst_userid)
        && equals(familyid, o.familyid)
        && equals(applyid, o.applyid)
        && equals(ctrl, o.ctrl);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (nickname != null ? nickname.hashCode() : 0);
      result = result * 37 + (requst_userid != null ? requst_userid.hashCode() : 0);
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (applyid != null ? applyid.hashCode() : 0);
      result = result * 37 + (ctrl != null ? ctrl.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_ADDFAM_REP> {

    public Integer roomid;
    public Long userid;
    public String nickname;
    public Long requst_userid;
    public Integer familyid;
    public Integer applyid;
    public ePB_ADDFAM_REPCMD ctrl;

    public Builder() {
    }

    public Builder(PB_USER_ADDFAM_REP message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.nickname = message.nickname;
      this.requst_userid = message.requst_userid;
      this.familyid = message.familyid;
      this.applyid = message.applyid;
      this.ctrl = message.ctrl;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ����ߵ�UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ����ߵ��ǳ�
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * �����UID
     */
    public Builder requst_userid(Long requst_userid) {
      this.requst_userid = requst_userid;
      return this;
    }

    /**
     * ����ID
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * ������Ϣid
     */
    public Builder applyid(Integer applyid) {
      this.applyid = applyid;
      return this;
    }

    /**
     * �ظ�����
     */
    public Builder ctrl(ePB_ADDFAM_REPCMD ctrl) {
      this.ctrl = ctrl;
      return this;
    }

    @Override
    public PB_USER_ADDFAM_REP build() {
      checkRequiredFields();
      return new PB_USER_ADDFAM_REP(this);
    }
  }
}
