// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �û���ȡ�������Ա
 */
public final class PB_USER_GET_TG_MEMBERS extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_TGID = 0L;
  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;

  /**
   * ������ID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long tgid;

  /**
   * ����ID
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * �û�UID
   */
  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long userid;

  public PB_USER_GET_TG_MEMBERS(Long tgid, Integer roomid, Long userid) {
    this.tgid = tgid;
    this.roomid = roomid;
    this.userid = userid;
  }

  private PB_USER_GET_TG_MEMBERS(Builder builder) {
    this(builder.tgid, builder.roomid, builder.userid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_GET_TG_MEMBERS)) return false;
    PB_USER_GET_TG_MEMBERS o = (PB_USER_GET_TG_MEMBERS) other;
    return equals(tgid, o.tgid)
        && equals(roomid, o.roomid)
        && equals(userid, o.userid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = tgid != null ? tgid.hashCode() : 0;
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_GET_TG_MEMBERS> {

    public Long tgid;
    public Integer roomid;
    public Long userid;

    public Builder() {
    }

    public Builder(PB_USER_GET_TG_MEMBERS message) {
      super(message);
      if (message == null) return;
      this.tgid = message.tgid;
      this.roomid = message.roomid;
      this.userid = message.userid;
    }

    /**
     * ������ID
     */
    public Builder tgid(Long tgid) {
      this.tgid = tgid;
      return this;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * �û�UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    @Override
    public PB_USER_GET_TG_MEMBERS build() {
      checkRequiredFields();
      return new PB_USER_GET_TG_MEMBERS(this);
    }
  }
}
