// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;

/**
 * ���б�ŵ��û���Ϣ
 */
public final class PB_USER_INFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_MSG_ID = 0L;

  @ProtoField(tag = 1)
  public final PB_USER user;

  @ProtoField(tag = 2, type = INT64)
  public final Long msg_id;

  public PB_USER_INFO(PB_USER user, Long msg_id) {
    this.user = user;
    this.msg_id = msg_id;
  }

  private PB_USER_INFO(Builder builder) {
    this(builder.user, builder.msg_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_INFO)) return false;
    PB_USER_INFO o = (PB_USER_INFO) other;
    return equals(user, o.user)
        && equals(msg_id, o.msg_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = user != null ? user.hashCode() : 0;
      result = result * 37 + (msg_id != null ? msg_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_INFO> {

    public PB_USER user;
    public Long msg_id;

    public Builder() {
    }

    public Builder(PB_USER_INFO message) {
      super(message);
      if (message == null) return;
      this.user = message.user;
      this.msg_id = message.msg_id;
    }

    public Builder user(PB_USER user) {
      this.user = user;
      return this;
    }

    public Builder msg_id(Long msg_id) {
      this.msg_id = msg_id;
      return this;
    }

    @Override
    public PB_USER_INFO build() {
      return new PB_USER_INFO(this);
    }
  }
}
