// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * ������ɢ����
 */
public final class PB_USER_DISMISS_FAMILY extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final Integer DEFAULT_FAMILYID = 0;

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * UID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �˳��ļ���ID
   */
  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer familyid;

  public PB_USER_DISMISS_FAMILY(Integer roomid, Long userid, Integer familyid) {
    this.roomid = roomid;
    this.userid = userid;
    this.familyid = familyid;
  }

  private PB_USER_DISMISS_FAMILY(Builder builder) {
    this(builder.roomid, builder.userid, builder.familyid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_DISMISS_FAMILY)) return false;
    PB_USER_DISMISS_FAMILY o = (PB_USER_DISMISS_FAMILY) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(familyid, o.familyid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_DISMISS_FAMILY> {

    public Integer roomid;
    public Long userid;
    public Integer familyid;

    public Builder() {
    }

    public Builder(PB_USER_DISMISS_FAMILY message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.familyid = message.familyid;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �˳��ļ���ID
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    @Override
    public PB_USER_DISMISS_FAMILY build() {
      checkRequiredFields();
      return new PB_USER_DISMISS_FAMILY(this);
    }
  }
}
