// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PB_USER_GET_NOTICE_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final eNOTICE_MSG_TYPE DEFAULT_NOTICETYPE = eNOTICE_MSG_TYPE.NOTICE_MSG_TYPE_FRD;

  /**
   * ����ID
   */
  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  /**
   * �������û�UID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * ֪ͨ����
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eNOTICE_MSG_TYPE noticeType;

  public PB_USER_GET_NOTICE_MSG(Integer roomid, Long userid, eNOTICE_MSG_TYPE noticeType) {
    this.roomid = roomid;
    this.userid = userid;
    this.noticeType = noticeType;
  }

  private PB_USER_GET_NOTICE_MSG(Builder builder) {
    this(builder.roomid, builder.userid, builder.noticeType);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_GET_NOTICE_MSG)) return false;
    PB_USER_GET_NOTICE_MSG o = (PB_USER_GET_NOTICE_MSG) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(noticeType, o.noticeType);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (noticeType != null ? noticeType.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_GET_NOTICE_MSG> {

    public Integer roomid;
    public Long userid;
    public eNOTICE_MSG_TYPE noticeType;

    public Builder() {
    }

    public Builder(PB_USER_GET_NOTICE_MSG message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.noticeType = message.noticeType;
    }

    /**
     * ����ID
     */
    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * �������û�UID
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * ֪ͨ����
     */
    public Builder noticeType(eNOTICE_MSG_TYPE noticeType) {
      this.noticeType = noticeType;
      return this;
    }

    @Override
    public PB_USER_GET_NOTICE_MSG build() {
      checkRequiredFields();
      return new PB_USER_GET_NOTICE_MSG(this);
    }
  }
}
