// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * //////////////////////
 * ��ȡָ�������û���Ϣ
 */
public final class PB_USER_GET_USERINFO extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ROOMID = 0;
  public static final Long DEFAULT_USERID = 0L;
  public static final Long DEFAULT_G_USERID = 0L;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer roomid;

  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long userid;

  @ProtoField(tag = 3, type = INT64, label = REQUIRED)
  public final Long g_userid;

  public PB_USER_GET_USERINFO(Integer roomid, Long userid, Long g_userid) {
    this.roomid = roomid;
    this.userid = userid;
    this.g_userid = g_userid;
  }

  private PB_USER_GET_USERINFO(Builder builder) {
    this(builder.roomid, builder.userid, builder.g_userid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_USER_GET_USERINFO)) return false;
    PB_USER_GET_USERINFO o = (PB_USER_GET_USERINFO) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(g_userid, o.g_userid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (g_userid != null ? g_userid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_USER_GET_USERINFO> {

    public Integer roomid;
    public Long userid;
    public Long g_userid;

    public Builder() {
    }

    public Builder(PB_USER_GET_USERINFO message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.g_userid = message.g_userid;
    }

    public Builder roomid(Integer roomid) {
      this.roomid = roomid;
      return this;
    }

    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    public Builder g_userid(Long g_userid) {
      this.g_userid = g_userid;
      return this;
    }

    @Override
    public PB_USER_GET_USERINFO build() {
      checkRequiredFields();
      return new PB_USER_GET_USERINFO(this);
    }
  }
}
