// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �ظ�web���سɹ���ʧ��
 */
public final class PB_WEB_FRIENDS_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_WEB_ADD_Ret DEFAULT_WEBADDRET = eRS_WEB_ADD_Ret.eRS_ADD_SUC;
  public static final List<PB_WEB_FRIENDS> DEFAULT_WEBFRDARRY = Collections.emptyList();

  /**
   * ����ֵ
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_WEB_ADD_Ret webAddret;

  /**
   * δ�ɹ����б�
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = PB_WEB_FRIENDS.class)
  public final List<PB_WEB_FRIENDS> webfrdArry;

  public PB_WEB_FRIENDS_REP(eRS_WEB_ADD_Ret webAddret, List<PB_WEB_FRIENDS> webfrdArry) {
    this.webAddret = webAddret;
    this.webfrdArry = immutableCopyOf(webfrdArry);
  }

  private PB_WEB_FRIENDS_REP(Builder builder) {
    this(builder.webAddret, builder.webfrdArry);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_WEB_FRIENDS_REP)) return false;
    PB_WEB_FRIENDS_REP o = (PB_WEB_FRIENDS_REP) other;
    return equals(webAddret, o.webAddret)
        && equals(webfrdArry, o.webfrdArry);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = webAddret != null ? webAddret.hashCode() : 0;
      result = result * 37 + (webfrdArry != null ? webfrdArry.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_WEB_FRIENDS_REP> {

    public eRS_WEB_ADD_Ret webAddret;
    public List<PB_WEB_FRIENDS> webfrdArry;

    public Builder() {
    }

    public Builder(PB_WEB_FRIENDS_REP message) {
      super(message);
      if (message == null) return;
      this.webAddret = message.webAddret;
      this.webfrdArry = copyOf(message.webfrdArry);
    }

    /**
     * ����ֵ
     */
    public Builder webAddret(eRS_WEB_ADD_Ret webAddret) {
      this.webAddret = webAddret;
      return this;
    }

    /**
     * δ�ɹ����б�
     */
    public Builder webfrdArry(List<PB_WEB_FRIENDS> webfrdArry) {
      this.webfrdArry = checkForNulls(webfrdArry);
      return this;
    }

    @Override
    public PB_WEB_FRIENDS_REP build() {
      checkRequiredFields();
      return new PB_WEB_FRIENDS_REP(this);
    }
  }
}
