// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �������
 */
public final class PB_WEB_DISS_REP extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_WEBUID = "";
  public static final Integer DEFAULT_FAMILYID = 0;
  public static final eRS_WEB_DISS_Ret DEFAULT_DRET = eRS_WEB_DISS_Ret.eRS_DISS_SUC;

  /**
   * web�û���ʶ
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String webuid;

  /**
   * ����id
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer familyid;

  /**
   * ����ֵ
   */
  @ProtoField(tag = 3, type = ENUM, label = REQUIRED)
  public final eRS_WEB_DISS_Ret dret;

  public PB_WEB_DISS_REP(String webuid, Integer familyid, eRS_WEB_DISS_Ret dret) {
    this.webuid = webuid;
    this.familyid = familyid;
    this.dret = dret;
  }

  private PB_WEB_DISS_REP(Builder builder) {
    this(builder.webuid, builder.familyid, builder.dret);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_WEB_DISS_REP)) return false;
    PB_WEB_DISS_REP o = (PB_WEB_DISS_REP) other;
    return equals(webuid, o.webuid)
        && equals(familyid, o.familyid)
        && equals(dret, o.dret);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = webuid != null ? webuid.hashCode() : 0;
      result = result * 37 + (familyid != null ? familyid.hashCode() : 0);
      result = result * 37 + (dret != null ? dret.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_WEB_DISS_REP> {

    public String webuid;
    public Integer familyid;
    public eRS_WEB_DISS_Ret dret;

    public Builder() {
    }

    public Builder(PB_WEB_DISS_REP message) {
      super(message);
      if (message == null) return;
      this.webuid = message.webuid;
      this.familyid = message.familyid;
      this.dret = message.dret;
    }

    /**
     * web�û���ʶ
     */
    public Builder webuid(String webuid) {
      this.webuid = webuid;
      return this;
    }

    /**
     * ����id
     */
    public Builder familyid(Integer familyid) {
      this.familyid = familyid;
      return this;
    }

    /**
     * ����ֵ
     */
    public Builder dret(eRS_WEB_DISS_Ret dret) {
      this.dret = dret;
      return this;
    }

    @Override
    public PB_WEB_DISS_REP build() {
      checkRequiredFields();
      return new PB_WEB_DISS_REP(this);
    }
  }
}
