// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �̼һ�ϵͳ���һ����Ϣ
 */
public final class PB_ZONE_LAST_MSG extends Message {
  private static final long serialVersionUID = 0L;

  public static final eRS_COMMON_ZONE DEFAULT_ZONE = eRS_COMMON_ZONE.eRS_COMMON_ZONE_AT;
  public static final String DEFAULT_CONTENT = "";
  public static final Long DEFAULT_TIME = 0L;
  public static final Integer DEFAULT_UNREADNUM = 0;
  public static final Integer DEFAULT_MSGID = 0;
  public static final String DEFAULT_TITLE = "";

  /**
   * ����
   */
  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final eRS_COMMON_ZONE zone;

  /**
   * ����
   */
  @ProtoField(tag = 2, type = STRING)
  public final String content;

  /**
   * ʱ��
   */
  @ProtoField(tag = 3, type = INT64)
  public final Long time;

  /**
   * δ����
   */
  @ProtoField(tag = 4, type = INT32)
  public final Integer unreadnum;

  /**
   * ��Ϣid
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer msgid;

  /**
   * �̼���
   */
  @ProtoField(tag = 6, type = STRING)
  public final String title;

  public PB_ZONE_LAST_MSG(eRS_COMMON_ZONE zone, String content, Long time, Integer unreadnum, Integer msgid, String title) {
    this.zone = zone;
    this.content = content;
    this.time = time;
    this.unreadnum = unreadnum;
    this.msgid = msgid;
    this.title = title;
  }

  private PB_ZONE_LAST_MSG(Builder builder) {
    this(builder.zone, builder.content, builder.time, builder.unreadnum, builder.msgid, builder.title);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ZONE_LAST_MSG)) return false;
    PB_ZONE_LAST_MSG o = (PB_ZONE_LAST_MSG) other;
    return equals(zone, o.zone)
        && equals(content, o.content)
        && equals(time, o.time)
        && equals(unreadnum, o.unreadnum)
        && equals(msgid, o.msgid)
        && equals(title, o.title);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = zone != null ? zone.hashCode() : 0;
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (time != null ? time.hashCode() : 0);
      result = result * 37 + (unreadnum != null ? unreadnum.hashCode() : 0);
      result = result * 37 + (msgid != null ? msgid.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ZONE_LAST_MSG> {

    public eRS_COMMON_ZONE zone;
    public String content;
    public Long time;
    public Integer unreadnum;
    public Integer msgid;
    public String title;

    public Builder() {
    }

    public Builder(PB_ZONE_LAST_MSG message) {
      super(message);
      if (message == null) return;
      this.zone = message.zone;
      this.content = message.content;
      this.time = message.time;
      this.unreadnum = message.unreadnum;
      this.msgid = message.msgid;
      this.title = message.title;
    }

    /**
     * ����
     */
    public Builder zone(eRS_COMMON_ZONE zone) {
      this.zone = zone;
      return this;
    }

    /**
     * ����
     */
    public Builder content(String content) {
      this.content = content;
      return this;
    }

    /**
     * ʱ��
     */
    public Builder time(Long time) {
      this.time = time;
      return this;
    }

    /**
     * δ����
     */
    public Builder unreadnum(Integer unreadnum) {
      this.unreadnum = unreadnum;
      return this;
    }

    /**
     * ��Ϣid
     */
    public Builder msgid(Integer msgid) {
      this.msgid = msgid;
      return this;
    }

    /**
     * �̼���
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    @Override
    public PB_ZONE_LAST_MSG build() {
      checkRequiredFields();
      return new PB_ZONE_LAST_MSG(this);
    }
  }
}
