// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * �̼����һ����Ϣ
 */
public final class PB_ZONE_MSG_LIST extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_USERID = 0L;
  public static final List<PB_ZONE_LAST_MSG> DEFAULT_LAST_LIST = Collections.emptyList();
  public static final Boolean DEFAULT_IS_END = false;

  /**
   * ������id
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long userid;

  /**
   * �������δ���б�
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = PB_ZONE_LAST_MSG.class)
  public final List<PB_ZONE_LAST_MSG> last_list;

  /**
   * �Ƿ������һ����
   */
  @ProtoField(tag = 3, type = BOOL)
  public final Boolean is_end;

  public PB_ZONE_MSG_LIST(Long userid, List<PB_ZONE_LAST_MSG> last_list, Boolean is_end) {
    this.userid = userid;
    this.last_list = immutableCopyOf(last_list);
    this.is_end = is_end;
  }

  private PB_ZONE_MSG_LIST(Builder builder) {
    this(builder.userid, builder.last_list, builder.is_end);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PB_ZONE_MSG_LIST)) return false;
    PB_ZONE_MSG_LIST o = (PB_ZONE_MSG_LIST) other;
    return equals(userid, o.userid)
        && equals(last_list, o.last_list)
        && equals(is_end, o.is_end);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (last_list != null ? last_list.hashCode() : 1);
      result = result * 37 + (is_end != null ? is_end.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PB_ZONE_MSG_LIST> {

    public Long userid;
    public List<PB_ZONE_LAST_MSG> last_list;
    public Boolean is_end;

    public Builder() {
    }

    public Builder(PB_ZONE_MSG_LIST message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.last_list = copyOf(message.last_list);
      this.is_end = message.is_end;
    }

    /**
     * ������id
     */
    public Builder userid(Long userid) {
      this.userid = userid;
      return this;
    }

    /**
     * �������δ���б�
     */
    public Builder last_list(List<PB_ZONE_LAST_MSG> last_list) {
      this.last_list = checkForNulls(last_list);
      return this;
    }

    /**
     * �Ƿ������һ����
     */
    public Builder is_end(Boolean is_end) {
      this.is_end = is_end;
      return this;
    }

    @Override
    public PB_ZONE_MSG_LIST build() {
      checkRequiredFields();
      return new PB_ZONE_MSG_LIST(this);
    }
  }
}
