// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\roomMsgs.proto
package com.hp.tcp.pb;

import com.squareup.wire.ProtoEnum;

public enum RS_Enter_RetCode
    implements ProtoEnum {
  /**
   * success
   */
  RS_LOGIN_SUCC(0),
  /**
   * user unexists
   */
  RS_LOGIN_NOUSER(1),
  /**
   * chat room unexists
   */
  RS_LOGIN_NOROOM(2),
  /**
   * token error
   */
  RS_LOGIN_TOKENERROR(3),
  /**
   * limit enter room
   */
  RS_LOGIN_LIMITENTER(4),
  /**
   * unknow
   */
  RS_LOGIN_UNKNOW(100),
  /**
   * visit memcached svr read enter room token fail
   */
  RS_LOGIN_MC_READTOKEN_FAIL(101),
  /**
   * visit db read user info fail
   */
  RS_LOGIN_DB_READUBI_FAIL(102),
  /**
   * visit db read room info fail
   */
  RS_LOGIN_DB_GETRI_FAIL(103);

  private final int value;

  RS_Enter_RetCode(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
